Cappuccino: AppKit/CoreGraphics/CGContextVML.j File Reference
AppKit/CoreGraphics/CGContextVML.j File Reference
Defines
#define COORD(aCoordinate) (ROUND(Z * (aCoordinate) - Z_2))
Functions
function CGBitmapGraphicsContextCreate ()
function CGContextClearRect (aContext, aRect)
function CGContextDrawImage (aContext, aRect, anImage)
function CGContextDrawPath (aContext, aMode)
function to_string (aColor)
function CGContextDrawLinearGradient (aContext, aGradient, aStartPoint, anEndPoint, options)
Variables
var VML_TRUTH_TABLE = [ "f", "t"]
var VML_LINECAP_TABLE = [ "flat", "round", "square" ]
var VML_LINEJOIN_TABLE = [ "miter", "round", "bevel" ]
var VML_ELEMENT_TABLE = [ " m ", " l ", "qb", " c ", " x ", [" at ", " wa "]]
var W = 10.0
var H = 10.0
var Z = 10.0
var Z_2 = Z / 2.0
Define Documentation
#define COORD (aCoordinate) (ROUND(Z * (aCoordinate) - Z_2))
Definition at line 57 of file CGContextVML.j.
Referenced by CGContextDrawPath().
Function Documentation
function CGBitmapGraphicsContextCreate ()
Definition at line 30 of file CGContextVML.j.
References CGBitmapGraphicsContextCreate().
function CGContextClearRect (aContext , aRect)
Definition at line 42 of file CGContextVML.j.
function CGContextDrawImage (aContext , aRect , anImage)
Definition at line 59 of file CGContextVML.j.
References CGPointApplyAffineTransform(), and CGRectApplyAffineTransform().
function CGContextDrawLinearGradient (aContext , aGradient , aStartPoint , anEndPoint , options)
Definition at line 271 of file CGContextVML.j.
References to_string().
function CGContextDrawPath (aContext , aMode)
Definition at line 110 of file CGContextVML.j.
References CGPathIsEmpty(), COORD, H, kCGPathElementAddArc, kCGPathElementAddCurveToPoint, kCGPathElementAddLineToPoint, kCGPathElementAddQuadCurveToPoint, kCGPathElementCloseSubpath, kCGPathElementMoveToPoint, kCGPathFill, kCGPathFillStroke, kCGPathStroke, VML_ELEMENT_TABLE, VML_LINECAP_TABLE, VML_LINEJOIN_TABLE, VML_TRUTH_TABLE, W, and Z.
function to_string (aColor)
Definition at line 266 of file CGContextVML.j.
Referenced by CGContextDrawLinearGradient().
Variable Documentation
var H = 10.0
Definition at line 53 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var VML_ELEMENT_TABLE = [ " m ", " l ", "qb", " c ", " x ", [" at ", " wa "]]
Definition at line 26 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var VML_LINECAP_TABLE = [ "flat", "round", "square" ]
Definition at line 24 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var VML_LINEJOIN_TABLE = [ "miter", "round", "bevel" ]
Definition at line 25 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var VML_TRUTH_TABLE = [ "f", "t"]
Definition at line 23 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var W = 10.0
Definition at line 52 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var Z = 10.0
Definition at line 54 of file CGContextVML.j.
Referenced by CGContextDrawPath().
var Z_2 = Z / 2.0
Definition at line 55 of file CGContextVML.j.