Cappuccino: AppKit/CoreGraphics/CGColor.j File Reference
AppKit/CoreGraphics/CGColor.j File Reference
Functions
function CFHashCode (aCFObject)
function CGColorGetConstantColor (aColorName)
function CGColorRetain (aColor)
function CGColorRelease ()
function CGColorCreate (aColorSpace, components)
function CGColorCreateCopy (aColor)
function CGColorCreateGenericGray (gray, alpha)
function CGColorCreateGenericRGB (red, green, blue, alpha)
function CGColorCreateGenericCMYK (cyan, magenta, yellow, black, alpha)
function CGColorCreateCopyWithAlpha (aColor, anAlpha)
function CGColorCreateWithPattern (aColorSpace, aPattern, components)
function CGColorEqualToColor (lhs, rhs)
function CGColorGetAlpha (aColor)
function CGColorGetColorSpace (aColor)
function CGColorGetComponents (aColor)
function CGColorGetNumberOfComponents (aColor)
function CGColorGetPattern (aColor)
Variables
import CGColorSpace j var CFTypeGlobalCount = 0
kCGColorWhite = "kCGColorWhite"
kCGColorBlack = "kCGColorBlack"
kCGColorClear = "kCGColorClear"
Function Documentation
function CFHashCode (aCFObject)
Definition at line 30 of file CGColor.j.
References CFTypeGlobalCount.
Referenced by CGColorCreate().
function CGColorCreate (aColorSpace , components)
Creates a new CGColor.
Parameters:
aColorSpace the CGColorSpace of the color
components the color's intensity values plus alpha
Returns:
CGColor the new color object CGColor
Definition at line 71 of file CGColor.j.
References CFHashCode(), and CGColorSpaceStandardizeComponents().
Referenced by CGColorCreateCopyWithAlpha(), CGColorCreateGenericCMYK(), CGColorCreateGenericGray(), CGColorCreateGenericRGB(), and CGGradientCreateWithColorComponents().
function CGColorCreateCopy (aColor)
Creates a copy of a color... but not really. CGColors are immutable, so to be efficient, this function will just return the same object that was passed in.
Parameters:
aColor the CGColor to 'copy'
Returns:
CGColor the color copy CGColor
Definition at line 96 of file CGColor.j.
function CGColorCreateCopyWithAlpha (aColor , anAlpha)
Creates a copy of the color with a specified alpha.
Parameters:
aColor the color object to copy
anAlpha the new alpha component for the copy (0.0-1.0).
Returns:
CGColor the new copy CGColor
Definition at line 150 of file CGColor.j.
References CGColorCreate(), and CGColorCreateWithPattern().
function CGColorCreateGenericCMYK (cyan , magenta , yellow , black , alpha)
Creates a CMYK color.
Parameters:
cyan the cyan component (0.0-1.0).
magenta the magenta component (0.0-1.0).
yellow the yellow component (0.0-1.0).
black the black component (0.0-1.0).
alpha the alpha component (0.0-1.0).
Returns:
CGColor the CMYK based color CGColor
Definition at line 138 of file CGColor.j.
References CGColorCreate().
function CGColorCreateGenericGray (gray , alpha)
Creates a gray color object.
Parameters:
gray the value to use for the color intensities (0.0-1.0).
alpha the gray's alpha value (0.0-1.0).
Returns:
CGColor the new gray color object CGColor
Definition at line 109 of file CGColor.j.
References CGColorCreate().
function CGColorCreateGenericRGB (red , green , blue , alpha)
Creates an RGB color.
Parameters:
red the red component (0.0-1.0)..
green the green component (0.0-1.0).
blue the blue component (0.0-1.0).
alpha the alpha component (0.0-1.0).
Returns:
CGColor the RGB based color CGColor
Definition at line 123 of file CGColor.j.
References CGColorCreate().
function CGColorCreateWithPattern (aColorSpace , aPattern , components)
Creates a color using the specified pattern.
Parameters:
aColorSpace the CGColorSpace
aPattern the pattern image
components the color components plus the alpha component
Returns:
CGColor the patterned color CGColor
Definition at line 175 of file CGColor.j.
Referenced by CGColorCreateCopyWithAlpha().
function CGColorEqualToColor (lhs , rhs)
Determines if two colors are the same.
Parameters:
lhs the first CGColor
rhs the second CGColor
Returns:
YES if the two colors are equal. NO otherwise.
Definition at line 190 of file CGColor.j.
function CGColorGetAlpha (aColor)
Returns the color's alpha component.
Parameters:
aColor the color
Returns:
float the alpha component (0.0-1.0). CGColor
Definition at line 224 of file CGColor.j.
function CGColorGetColorSpace (aColor)
Returns the CGColor's color space.
Returns:
CGColorSpace CGColor
Definition at line 236 of file CGColor.j.
function CGColorGetComponents (aColor)
Returns the CGColor's components including the alpha in an array.
Parameters:
aColor the color
Returns:
CPArray the color's components
Definition at line 247 of file CGColor.j.
function CGColorGetConstantColor (aColorName)
Definition at line 44 of file CGColor.j.
function CGColorGetNumberOfComponents (aColor)
Returns the number of color components (including alpha) in the specified color.
Parameters:
aColor the CGColor
Returns:
CPNumber the number of components CGColor
Definition at line 259 of file CGColor.j.
function CGColorGetPattern (aColor)
Gets the CGColor's pattern.
Parameters:
a CGColor
Returns:
CGPatternFIXME the pattern image CGColor
Definition at line 270 of file CGColor.j.
function CGColorRelease ()
This function is for source compatability.
Definition at line 60 of file CGColor.j.
function CGColorRetain (aColor)
This function is for source compatability.
Definition at line 52 of file CGColor.j.
Variable Documentation
import CGColorSpace j var CFTypeGlobalCount = 0
Definition at line 28 of file CGColor.j.
Referenced by CFHashCode().
kCGColorBlack = "kCGColorBlack"
Definition at line 39 of file CGColor.j.
kCGColorClear = "kCGColorClear"
Definition at line 40 of file CGColor.j.
kCGColorWhite = "kCGColorWhite"
Definition at line 38 of file CGColor.j.