Cappuccino: AppKit/CoreGraphics/CGGradient.j File Reference
AppKit/CoreGraphics/CGGradient.j File Reference
Functions
function CGGradientCreateWithColorComponents (aColorSpace, components, locations, count)
function CGGradientCreateWithColors (aColorSpace, colors, locations)
function CGGradientRelease ()
function CGGradientRetain (aGradient)
Variables
import CGColor j import
CGColorSpace j kCGGradientDrawsBeforeStartLocation = 1 << 0
kCGGradientDrawsAfterEndLocation = 1 << 1
Function Documentation
function CGGradientCreateWithColorComponents (aColorSpace , components , locations , count)
Definition at line 30 of file CGGradient.j.
References CGColorCreate(), and CGGradientCreateWithColors().
function CGGradientCreateWithColors (aColorSpace , colors , locations)
Definition at line 46 of file CGGradient.j.
Referenced by CGGradientCreateWithColorComponents().
function CGGradientRelease ()
Definition at line 51 of file CGGradient.j.
function CGGradientRetain (aGradient)
Definition at line 55 of file CGGradient.j.
Variable Documentation
kCGGradientDrawsAfterEndLocation = 1 << 1
Definition at line 28 of file CGGradient.j.
import CGColor j import CGColorSpace j kCGGradientDrawsBeforeStartLocation = 1 << 0
Definition at line 27 of file CGGradient.j.