Cappuccino: CPCollectionView Class Reference
CPCollectionView Class Reference
[AppKit]
Public Member Functions
(id) - initWithFrame: [implementation]
(void) - setItemPrototype: [implementation]
(CPCollectionViewItem) - itemPrototype [implementation]
(CPCollectionViewItem) - newItemForRepresentedObject: [implementation]
(BOOL) - acceptsFirstResponder [implementation]
(BOOL) - isFirstResponder [implementation]
(void) - setContent: [implementation]
(CPArray) - content [implementation]
(CPArray) - items [implementation]
(void) - setSelectable: [implementation]
(BOOL) - isSelectable [implementation]
(void) - setAllowsEmptySelection: [implementation]
(BOOL) - allowsEmptySelection [implementation]
(void) - setAllowsMultipleSelection: [implementation]
(BOOL) - allowsMultipleSelection [implementation]
(void) - setSelectionIndexes: [implementation]
(CPIndexSet) - selectionIndexes [implementation]
(void) - reloadContent [implementation]
(void) - tile [implementation]
(void) - resizeSubviewsWithOldSize: [implementation]
(void) - setMaxNumberOfRows: [implementation]
(unsigned) - maxNumberOfRows [implementation]
(void) - setMaxNumberOfColumns: [implementation]
(unsigned) - maxNumberOfColumns [implementation]
(unsigned) - numberOfRows [implementation]
(unsigned) - numberOfColumns [implementation]
(void) - setMinItemSize: [implementation]
(CGSize) - minItemSize [implementation]
(void) - setMaxItemSize: [implementation]
(CGSize) - maxItemSize [implementation]
(void) - setBackgroundColors: [implementation]
(CPArray) - backgroundColors [implementation]
(void) - mouseUp: [implementation]
(void) - mouseDown: [implementation]
(void) - mouseDragged: [implementation]
(void) - pasteboard:provideDataForType: [implementation]
(void) - setVerticalMargin: [implementation]
(float) - verticalMargin [implementation]
(void) - setDelegate: [implementation]
(id) - delegate [implementation]
(id) - initWithCoder: [implementation]
(void) - encodeWithCoder: [implementation]
Detailed Description
This class displays an array as a grid of objects, where each object is represented by a view. The view is controlled by creating a CPCollectionViewItem and specifying its view, then setting that item as the collection view prototype.
Delegate Methods
-(void)collectionViewDidChangeSelection:(CPCollectionView)collectionView; Called when the selection in the collection view has changed.
Parameters:
collectionView the collection view who's selection changed
-(void)collectionView:(CPCollectionView)collectionView didDoubleClickOnItemAtIndex:(int)index; Called when the user double-clicks on an item in the collection view.
Parameters:
collectionView the collection view that received the double-click
index the index of the item that received the double-click
-(CPData)collectionView:(CPCollectionView)collectionView dataForItemsAtIndexes:(CPIndexSet)indices forType:(CPString)aType; Invoked to obtain data for a set of indices.
Parameters:
collectionView the collection view to obtain data for
indices the indices to return data for
aType the data type
Returns:
a data object containing the index items
-(CPArray)collectionView:(CPCollectionView)collectionView dragTypesForItemsAtIndexes:(CPIndexSet)indices; Invoked to obtain the data types supported by the specified indices for placement on the pasteboard.
Parameters:
collectionView the collection view the items reside in
indices the indices to obtain drag types
Returns:
an array of drag types (CPString)
Definition at line 66 of file CPCollectionView.j.
Member Function Documentation
- (BOOL) acceptsFirstResponder [implementation]
Returns YES by default.
Definition at line 184 of file CPCollectionView.j.
- (BOOL) allowsEmptySelection [implementation]
Returns YES if the user can select no items, NO otherwise.
Definition at line 272 of file CPCollectionView.j.
- (BOOL) allowsMultipleSelection [implementation]
Returns YES if the user can select multiple items, NO otherwise.
Definition at line 289 of file CPCollectionView.j.
- (CPArray) backgroundColors [implementation]
Definition at line 558 of file CPCollectionView.j.
- (CPArray) content [implementation]
Returns the collection view content array
Definition at line 217 of file CPCollectionView.j.
- (id) delegate [implementation]
Returns the collection view's delegate
Definition at line 668 of file CPCollectionView.j.
- (void) encodeWithCoder: (CPCoder) aCoder [implementation]
Definition at line 716 of file CPCollectionView.j.
References CGSizeEqualToSize(), and CGSizeMakeZero().
- (id) initWithCoder: (CPCoder) aCoder [implementation]
Definition at line 684 of file CPCollectionView.j.
References CGSizeMakeZero(), CPIndexSet::indexSet, and setBackgroundColors:.
- (id) initWithFrame: (CGRect) aFrame [implementation]
Definition at line 104 of file CPCollectionView.j.
References CGSizeMakeZero(), CPIndexSet::indexSet, and setBackgroundColors:.
- (BOOL) isFirstResponder [implementation]
Returns whether the receiver is currently the first responder.
Definition at line 192 of file CPCollectionView.j.
- (BOOL) isSelectable [implementation]
Returns YES if the collection view is selectable, and NO otherwise.
Definition at line 255 of file CPCollectionView.j.
- (CPCollectionViewItem) itemPrototype [implementation]
Returns the current item prototype
Definition at line 149 of file CPCollectionView.j.
- (CPArray) items [implementation]
Returns the collection view items.
Definition at line 225 of file CPCollectionView.j.
- (CGSize) maxItemSize [implementation]
Returns the current maximum item size.
Definition at line 534 of file CPCollectionView.j.
- (unsigned) maxNumberOfColumns [implementation]
Returns the maximum number of columns
Definition at line 473 of file CPCollectionView.j.
- (unsigned) maxNumberOfRows [implementation]
Returns the maximum number of rows.
Definition at line 451 of file CPCollectionView.j.
- (CGSize) minItemSize [implementation]
Returns the current minimum item size
Definition at line 512 of file CPCollectionView.j.
- (void) mouseDown: (CPEvent) anEvent [implementation]
Definition at line 569 of file CPCollectionView.j.
References CPIndexSet::indexSet, CPIndexSet::indexSetWithIndex:, CPEvent::locationInWindow, and setSelectionIndexes:.
- (void) mouseDragged: (CPEvent) anEvent [implementation]
Definition at line 585 of file CPCollectionView.j.
References CPPasteboard::declareTypes:owner:, CPEvent::locationInWindow, newItemForRepresentedObject:, and CPPasteboard::pasteboardWithName:.
- (void) mouseUp: (CPEvent) anEvent [implementation]
Definition at line 563 of file CPCollectionView.j.
- (CPCollectionViewItem) newItemForRepresentedObject: (id) anObject [implementation]
Returns a collection view item for anObject.
Parameters:
anObject the object to be represented.
Definition at line 158 of file CPCollectionView.j.
References CPKeyedArchiver::archivedDataWithRootObject:, and CPKeyedUnarchiver::unarchiveObjectWithData:.
Referenced by mouseDragged:.
- (unsigned) numberOfColumns [implementation]
Returns the current number of columns
Definition at line 490 of file CPCollectionView.j.
- (unsigned) numberOfRows [implementation]
Returns the current number of rows
Definition at line 481 of file CPCollectionView.j.
- (void) pasteboard: (CPPasteboard) aPasteboard provideDataForType: (CPString) aType [implementation]
Places the selected items on the specified pasteboard. The items are requested from the collection's delegate.
Parameters:
aPasteboard the pasteboard to put the items on
aType the format the pasteboard data
Definition at line 625 of file CPCollectionView.j.
References CPPasteboard::setData:forType:.
- (void) reloadContent [implementation]
Definition at line 328 of file CPCollectionView.j.
References tile.
Referenced by setContent:, and setItemPrototype:.
- (void) resizeSubviewsWithOldSize: (CGSize) aSize [implementation]
Definition at line 428 of file CPCollectionView.j.
References tile.
- (CPIndexSet) selectionIndexes [implementation]
Returns a set of the selected indices.
Definition at line 322 of file CPCollectionView.j.
- (void) setAllowsEmptySelection: (BOOL) shouldAllowEmptySelection [implementation]
Sets whether the user may have no items selected. If YES, mouse clicks not on any item will empty the current selection. The first item will also start off as selected.
Parameters:
shouldAllowMultipleSelection YES allows the user to select multiple items
Definition at line 264 of file CPCollectionView.j.
- (void) setAllowsMultipleSelection: (BOOL) shouldAllowMultipleSelection [implementation]
Sets whether the user can select multiple items.
Parameters:
shouldAllowMultipleSelection YES allows the user to select multiple items
Definition at line 281 of file CPCollectionView.j.
- (void) setBackgroundColors: (CPArray) backgroundColors [implementation]
Definition at line 539 of file CPCollectionView.j.
Referenced by initWithCoder:, and initWithFrame:.
- (void) setContent: (CPArray) anArray [implementation]
Sets the content of the collection view to the content in anArray. This array can be of any type, and each element will be passed to the -setRepresentedObject: method. It's the responsibility of your custom collection view item to interpret the object.
Parameters:
anArray the content array
Definition at line 204 of file CPCollectionView.j.
References reloadContent.
- (void) setDelegate: (id) aDelegate [implementation]
Sets the collection view's delegate
Parameters:
aDelegate the new delegate
Definition at line 660 of file CPCollectionView.j.
- (void) setItemPrototype: (CPCollectionViewItem) anItem [implementation]
Sets the item prototype to anItem
Parameters:
anItem the new item prototype
Definition at line 136 of file CPCollectionView.j.
References reloadContent.
- (void) setMaxItemSize: (CGSize) aSize [implementation]
Sets the maximum item size.
Parameters:
aSize the new maximum item size
Definition at line 521 of file CPCollectionView.j.
References CGSizeEqualToSize(), CGSizeMakeCopy(), and tile.
- (void) setMaxNumberOfColumns: (unsigned) aMaxNumberOfColumns [implementation]
Sets the maximum number of columns.
Parameters:
aMaxNumberOfColumns the new maximum number of columns
Definition at line 460 of file CPCollectionView.j.
References tile.
- (void) setMaxNumberOfRows: (unsigned) aMaxNumberOfRows [implementation]
Sets the maximum number of rows.
Parameters:
aMaxNumberOfRows the new maximum number of rows
Definition at line 438 of file CPCollectionView.j.
References tile.
- (void) setMinItemSize: (CGSize) aSize [implementation]
Sets the minimum size for an item
Parameters:
aSize the new minimum item size
Definition at line 499 of file CPCollectionView.j.
References CGSizeEqualToSize(), CGSizeMakeCopy(), and tile.
- (void) setSelectable: (BOOL) isSelectable [implementation]
Sets whether the user is allowed to select items
Parameters:
isSelectable YES allows the user to select items.
Definition at line 235 of file CPCollectionView.j.
References CPNotFound.
- (void) setSelectionIndexes: (CPIndexSet) anIndexSet [implementation]
Sets the selected items based on the provided indices.
Parameters:
anIndexSet the set of items to be selected
Definition at line 298 of file CPCollectionView.j.
References CPNotFound.
Referenced by mouseDown:.
- (void) setVerticalMargin: (float) aVerticalMargin [implementation]
Sets the collection view's vertical spacing between elements.
Parameters:
aVerticalMargin the number of pixels to place between elements
Definition at line 637 of file CPCollectionView.j.
References tile.
- (void) tile [implementation]
Definition at line 359 of file CPCollectionView.j.
References CGRectGetWidth(), CGSizeEqualToSize(), CGSizeMakeCopy(), MAX, MIN, and width.
Referenced by reloadContent, resizeSubviewsWithOldSize:, setMaxItemSize:, setMaxNumberOfColumns:, setMaxNumberOfRows:, setMinItemSize:, and setVerticalMargin:.
- (float) verticalMargin [implementation]
Gets the collection view's current vertical spacing between elements.
Definition at line 651 of file CPCollectionView.j.
The documentation for this class was generated from the following file:
AppKit/CPCollectionView.j