Cappuccino: CPClipView Class Reference
CPClipView Class Reference
[AppKit]
Public Member Functions
(void) - setDocumentView: [implementation]
(id) - documentView [implementation]
(CGPoint) - constrainScrollPoint: [implementation]
(void) - setBoundsOrigin: [implementation]
(void) - scrollToPoint: [implementation]
(void) - viewBoundsChanged: [implementation]
(void) - viewFrameChanged: [implementation]
(void) - resizeSubviewsWithOldSize: [implementation]
(BOOL) - autoscroll: [implementation]
(id) - initWithCoder: [implementation]
(void) - encodeWithCoder: [implementation]
Detailed Description
CPClipView allows you to define a clip rect and display only that portion of its containing view. It is used to hold the document view in a CPScrollView.
Definition at line 35 of file CPClipView.j.
Member Function Documentation
- (BOOL) autoscroll: (CPEvent) anEvent [implementation]
Definition at line 182 of file CPClipView.j.
References CGRectMakeZero(), CPRectContainsPoint(), CPSizeMake(), and CPEvent::locationInWindow.
- (CGPoint) constrainScrollPoint: (CGPoint) aPoint [implementation]
Returns a new point that may be adjusted from aPoint to make sure it lies within the document view.
Parameters:
aPoint
Returns:
the adjusted point
Definition at line 103 of file CPClipView.j.
References MAX, and MIN.
Referenced by scrollToPoint:.
- (id) documentView [implementation]
Returns the document view.
Definition at line 92 of file CPClipView.j.
Referenced by CPScrollView::setContentView:.
- (void) encodeWithCoder: (CPCoder) aCoder [implementation]
Definition at line 213 of file CPClipView.j.
- (id) initWithCoder: (CPCoder) aCoder [implementation]
Definition at line 205 of file CPClipView.j.
References setDocumentView:.
- (void) resizeSubviewsWithOldSize: (CGSize) aSize [implementation]
Definition at line 156 of file CPClipView.j.
- (void) scrollToPoint: (CGPoint) aPoint [implementation]
Scrolls the clip view to the specified point. The method sets its bounds origin to aPoint.
Definition at line 133 of file CPClipView.j.
References constrainScrollPoint:, and setBoundsOrigin:.
Referenced by CPView::scrollClipView:toPoint:.
- (void) setBoundsOrigin: (CGPoint) aPoint [implementation]
Definition at line 116 of file CPClipView.j.
Referenced by scrollToPoint:.
- (void) setDocumentView: (CPView) aView [implementation]
Sets the document view to be aView.
Parameters:
aView the new document view. It's frame origin will be changed to (0,0) after calling this method.
Definition at line 44 of file CPClipView.j.
References CPNotificationCenter::defaultCenter.
Referenced by initWithCoder:.
- (void) viewBoundsChanged: (CPNotification) aNotification [implementation]
Handles a CPViewBoundsDidChangeNotification.
Parameters:
aNotification the notification event
Definition at line 142 of file CPClipView.j.
- (void) viewFrameChanged: (CPNotification) aNotification [implementation]
Handles a CPViewFrameDidChangeNotification.
Parameters:
aNotification the notification event
Definition at line 151 of file CPClipView.j.
The documentation for this class was generated from the following file:
AppKit/CPClipView.j