Cappuccino: CPBox Class Reference
CPBox Class Reference
Public Member Functions
(id) - initWithFrame: [implementation]
(CPRect) - borderRect [implementation]
(CPBorderType) - borderType [implementation]
(void) - setBorderType: [implementation]
(CPColor) - borderColor [implementation]
(void) - setBorderColor: [implementation]
(float) - borderWidth [implementation]
(void) - setBorderWidth: [implementation]
(float) - cornerRadius [implementation]
(void) - setCornerRadius: [implementation]
(CPColor) - fillColor [implementation]
(void) - setFillColor: [implementation]
(CPView) - contentView [implementation]
(void) - setContentView: [implementation]
(CPSize) - contentViewMargins [implementation]
(void) - setContentViewMargins: [implementation]
(void) - setFrameFromContentFrame: [implementation]
(void) - sizeToFit [implementation]
(void) - drawRect: [implementation]
Static Public Member Functions
(id) + boxEnclosingView: [implementation]
Detailed Description
Definition at line 31 of file CPBox.j.
Member Function Documentation
- (CPColor) borderColor [implementation]
Definition at line 97 of file CPBox.j.
- (CPRect) borderRect [implementation]
Definition at line 81 of file CPBox.j.
- (CPBorderType) borderType [implementation]
Definition at line 86 of file CPBox.j.
- (float) borderWidth [implementation]
Definition at line 111 of file CPBox.j.
+ (id) boxEnclosingView: (CPView) aView [implementation]
Definition at line 45 of file CPBox.j.
References CPView::frame, and CPView::superview.
- (CPView) contentView [implementation]
Definition at line 153 of file CPBox.j.
- (CPSize) contentViewMargins [implementation]
Definition at line 169 of file CPBox.j.
- (float) cornerRadius [implementation]
Definition at line 125 of file CPBox.j.
- (void) drawRect: (CPRect) rect [implementation]
Definition at line 199 of file CPBox.j.
References CGContextAddLineToPoint(), CGContextBeginPath(), CGContextFillRoundedRectangleInRect(), CGContextMoveToPoint(), CGContextSetFillColor(), CGContextSetLineWidth(), CGContextSetStrokeColor(), CGContextStrokePath(), CGContextStrokeRoundedRectangleInRect(), CGRectGetMaxX(), CGRectGetMaxY(), CGRectGetMinX(), CGRectGetMinY(), CGRectMake(), CPBezelBorder, CPLineBorder, CPGraphicsContext::currentContext, and CPGraphicsContext::graphicsPort.
- (CPColor) fillColor [implementation]
Definition at line 139 of file CPBox.j.
- (id) initWithFrame: (CPRect) frameRect [implementation]
Definition at line 59 of file CPBox.j.
References CGSizeMake().
- (void) setBorderColor: (CPColor) color [implementation]
Definition at line 102 of file CPBox.j.
- (void) setBorderType: (CPBorderType) value [implementation]
Definition at line 91 of file CPBox.j.
- (void) setBorderWidth: (float) width [implementation]
Definition at line 116 of file CPBox.j.
References width.
- (void) setContentView: (CPView) aView [implementation]
Definition at line 158 of file CPBox.j.
References CPView::setFrame:.
- (void) setContentViewMargins: (CPSize) size [implementation]
Definition at line 174 of file CPBox.j.
References CGSizeMakeCopy(), CPException::raise:reason:, and size.
- (void) setCornerRadius: (float) radius [implementation]
Definition at line 130 of file CPBox.j.
- (void) setFillColor: (CPColor) color [implementation]
Definition at line 144 of file CPBox.j.
- (void) setFrameFromContentFrame: (CPRect) aRect [implementation]
Definition at line 183 of file CPBox.j.
- (void) sizeToFit [implementation]
Definition at line 189 of file CPBox.j.
The documentation for this class was generated from the following file:
AppKit/CPBox.j