Cappuccino: CPKeyedUnarchiver Class Reference
CPKeyedUnarchiver Class Reference
[Foundation]
Unarchives objects created using CPKeyedArchiver.
Public Member Functions
(id) - initForReadingWithData: [implementation]
(BOOL) - containsValueForKey: [implementation]
(BOOL) - decodeBoolForKey: [implementation]
(float) - decodeFloatForKey: [implementation]
(double) - decodeDoubleForKey: [implementation]
(int) - decodeIntForKey: [implementation]
(CGPoint) - decodePointForKey: [implementation]
(CGRect) - decodeRectForKey: [implementation]
(CGSize) - decodeSizeForKey: [implementation]
(id) - decodeObjectForKey: [implementation]
(id) - decodeBytesForKey: [implementation]
(void) - finishDecoding [implementation]
(id) - delegate [implementation]
(void) - setDelegate: [implementation]
(void) - setClass:forClassName: [implementation]
(Class) - classForClassName: [implementation]
(BOOL) - allowsKeyedCoding [implementation]
Static Public Member Functions
(void) + initialize [implementation]
(id) + unarchiveObjectWithData: [implementation]
(id) + unarchiveObjectWithFile: [implementation]
(id) + unarchiveObjectWithFile:asynchronously: [implementation]
Detailed Description
Unarchives objects created using CPKeyedArchiver.
CPKeyedUnarchiver is used for creating objects out of coded files or CPData objects that were created by CPKeyedArchiver. More specifically, this class unarchives objects from a data stream or file and brings them back into memory for programmatic usage.
-(Class)unarchiver:(CPKeyedUnarchiver)unarchiver cannotDecodeObjectOfClassName:(CPString)name originalClasses:(CPArray)classNames; Called when the specified class is not available during decoding. The delegate may load the class, or return a substitute class to use instead.
Parameters:
unarchiver the unarchiver performing the decode
name the name of the class that can't be found
an array of class names describing the encoded object's class hierarchy. The first index is the encoded class name, and each superclass is after that.
Returns:
the Class to use instead or nil to abort the unarchiving operation
-(id)unarchiver:(CPKeyedUnarchiver)unarchiver didDecodeObject:(id)object; Called when the unarchiver decodes an object.
Parameters:
unarchiver the unarchiver doing the decoding
object the decoded objec
Returns:
a substitute to use for the decoded object. This can be the same object argument provide, another object or nil.
-(void)unarchiver:(CPKeyedUnarchiver)unarchiver willReplaceObject:(id)object withObject:(id)newObject; Called when a decoded object has been substituted with another. (for example, from -unarchiver:didDecodeObject:.
Parameters:
unarchiver the unarchiver that decoded the object
object the original decoded object
newObject the replacement object
-(void)unarchiverWillFinish:(CPKeyedUnarchiver)unarchiver; Called when the unarchiver is about to finish decoding.
Parameters:
unarchiver the unarchiver that's about to finish
-(void)unarchiverDidFinish:(CPKeyedUnarchiver)unarchiver; Called when the unarchiver has finished decoding.
Parameters:
unarchiver the unarchiver that finished decoding
Definition at line 102 of file CPKeyedUnarchiver.j.
Member Function Documentation
- (BOOL) allowsKeyedCoding [implementation]
Definition at line 405 of file CPKeyedUnarchiver.j.
- (Class) classForClassName: (CPString) aClassName [implementation]
Definition at line 400 of file CPKeyedUnarchiver.j.
- (BOOL) containsValueForKey: (CPString) aKey [implementation]
Definition at line 190 of file CPKeyedUnarchiver.j.
- (BOOL) decodeBoolForKey: (CPString) aKey [implementation]
Definition at line 220 of file CPKeyedUnarchiver.j.
References decodeObjectForKey:.
- (id) decodeBytesForKey: (CPString) aKey [implementation]
Definition at line 337 of file CPKeyedUnarchiver.j.
References decodeObjectForKey:.
- (double) decodeDoubleForKey: (CPString) aKey [implementation]
Definition at line 240 of file CPKeyedUnarchiver.j.
References decodeObjectForKey:.
- (float) decodeFloatForKey: (CPString) aKey [implementation]
Definition at line 230 of file CPKeyedUnarchiver.j.
References decodeObjectForKey:.
- (int) decodeIntForKey: (CPString) aKey [implementation]
Definition at line 250 of file CPKeyedUnarchiver.j.
References decodeObjectForKey:.
- (id) decodeObjectForKey: (CPString) aKey [implementation]
Definition at line 305 of file CPKeyedUnarchiver.j.
Referenced by decodeBoolForKey:, decodeBytesForKey:, decodeDoubleForKey:, decodeFloatForKey:, decodeIntForKey:, decodePointForKey:, decodeRectForKey:, and decodeSizeForKey:.
- (CGPoint) decodePointForKey: (CPString) aKey [implementation]
Definition at line 260 of file CPKeyedUnarchiver.j.
References CPPointFromString(), CPPointMake(), and decodeObjectForKey:.
- (CGRect) decodeRectForKey: (CPString) aKey [implementation]
Definition at line 275 of file CPKeyedUnarchiver.j.
References CPRectFromString(), CPRectMakeZero(), and decodeObjectForKey:.
- (CGSize) decodeSizeForKey: (CPString) aKey [implementation]
Definition at line 290 of file CPKeyedUnarchiver.j.
References CPSizeFromString(), CPSizeMake(), and decodeObjectForKey:.
- (id) delegate [implementation]
Definition at line 363 of file CPKeyedUnarchiver.j.
- (void) finishDecoding [implementation]
Definition at line 351 of file CPKeyedUnarchiver.j.
- (id) initForReadingWithData: (CPData) data [implementation]
Definition at line 139 of file CPKeyedUnarchiver.j.
References CPArray::arrayWithObject:, CPDictionary::dictionary, and CPData::plistObject.
+ (void) initialize [implementation]
Definition at line 121 of file CPKeyedUnarchiver.j.
- (void) setClass: (Class) aClass forClassName: (CPString) aClassName [implementation]
Definition at line 395 of file CPKeyedUnarchiver.j.
- (void) setDelegate: (id) aDelegate [implementation]
Definition at line 372 of file CPKeyedUnarchiver.j.
References CPKeyedUnarchiverDelegate_unarchiver_cannotDecodeObjectOfClassName_originalClasses_.
+ (id) unarchiveObjectWithData: (CPData) data [implementation]
Definition at line 162 of file CPKeyedUnarchiver.j.
Referenced by CPToolbarItem::copy, CPCollectionView::newItemForRepresentedObject:, and CPImageView::performDragOperation:.
+ (id) unarchiveObjectWithFile: (CPString) aFilePath [implementation]
Definition at line 175 of file CPKeyedUnarchiver.j.
+ (id) unarchiveObjectWithFile: (CPString) aFilePath asynchronously: (BOOL) aFlag [implementation]
Definition at line 182 of file CPKeyedUnarchiver.j.
The documentation for this class was generated from the following file:
Foundation/CPKeyedUnarchiver.j