Cappuccino: CPWindow Class Reference
CPWindow Class Reference
[AppKit]
Public Member Functions
(id) - init [implementation]
(id) - initWithContentRect:styleMask: [implementation]
(CPPlatformWindow) - platformWindow [implementation]
(void) - setPlatformWindow: [implementation]
(void) - awakeFromCib [implementation]
(void) - setFullPlatformWindow: [implementation]
(BOOL) - isFullPlatformWindow [implementation]
(unsigned) - styleMask [implementation]
(CGRect) - contentRectForFrameRect: [implementation]
(CGRect) - frameRectForContentRect: [implementation]
(CGRect) - frame [implementation]
(void) - setFrame:display:animate: [implementation]
(void) - setFrame:display: [implementation]
(void) - setFrame: [implementation]
(void) - setFrameOrigin: [implementation]
(void) - setFrameSize: [implementation]
(void) - orderFront: [implementation]
(void) - orderBack: [implementation]
(void) - orderOut: [implementation]
(void) - orderWindow:relativeTo: [implementation]
(void) - setLevel: [implementation]
(int) - level [implementation]
(BOOL) - isVisible [implementation]
(BOOL) - showsResizeIndicator [implementation]
(void) - setShowsResizeIndicator: [implementation]
(CGSize) - resizeIndicatorOffset [implementation]
(void) - setResizeIndicatorOffset: [implementation]
(void) - setContentView: [implementation]
(CPView) - contentView [implementation]
(void) - setBackgroundColor: [implementation]
(CPColor) - backgroundColor [implementation]
(void) - setMinSize: [implementation]
(CGSize) - minSize [implementation]
(void) - setMaxSize: [implementation]
(CGSize) - maxSize [implementation]
(BOOL) - hasShadow [implementation]
(void) - setHasShadow: [implementation]
(void) - setShadowStyle: [implementation]
(void) - setDelegate: [implementation]
(id) - delegate [implementation]
(void) - setWindowController: [implementation]
(CPWindowController) - windowController [implementation]
(void) - doCommandBySelector: [implementation]
(BOOL) - acceptsFirstResponder [implementation]
(void) - makeFirstResponder: [implementation]
(CPResponder) - firstResponder [implementation]
(BOOL) - acceptsMouseMovedEvents [implementation]
(void) - setAcceptsMouseMovedEvents: [implementation]
(BOOL) - ignoresMouseEvents [implementation]
(void) - setIgnoresMouseEvents: [implementation]
(CPString) - title [implementation]
(void) - setTitle: [implementation]
(void) - setTitleWithRepresentedFilename: [implementation]
(void) - setRepresentedFilename: [implementation]
(CPString) - representedFilename [implementation]
(void) - setRepresentedURL: [implementation]
(CPURL) - representedURL [implementation]
(CPScreen) - screen [implementation]
(void) - setMovableByWindowBackground: [implementation]
(BOOL) - isMovableByWindowBackground [implementation]
(void) - center [implementation]
(void) - sendEvent: [implementation]
(int) - windowNumber [implementation]
(void) - becomeKeyWindow [implementation]
(BOOL) - canBecomeKeyWindow [implementation]
(BOOL) - isKeyWindow [implementation]
(void) - makeKeyAndOrderFront: [implementation]
(void) - makeKeyWindow [implementation]
(void) - resignKeyWindow [implementation]
(void) - dragImage:at:offset:event:pasteboard:source:slideBack: [implementation]
(void) - dragView:at:offset:event:pasteboard:source:slideBack: [implementation]
(void) - registerForDraggedTypes: [implementation]
(CPArray) - registeredDraggedTypes [implementation]
(void) - unregisterDraggedTypes [implementation]
(void) - setDocumentEdited: [implementation]
(BOOL) - isDocumentEdited [implementation]
(void) - setDocumentSaving: [implementation]
(BOOL) - isDocumentSaving [implementation]
(void) - performMiniaturize: [implementation]
(void) - miniaturize: [implementation]
(void) - deminiaturize: [implementation]
(void) - isMiniaturized [implementation]
(void) - performClose: [implementation]
(void) - close [implementation]
(BOOL) - isMainWindow [implementation]
(BOOL) - canBecomeMainWindow [implementation]
(void) - makeMainWindow [implementation]
(void) - becomeMainWindow [implementation]
(void) - resignMainWindow [implementation]
(CPToolbar) - toolbar [implementation]
(void) - setToolbar: [implementation]
(void) - toggleToolbarShown: [implementation]
(void) - animationDidEnd: [implementation]
(CPWindow) - attachedSheet [implementation]
(BOOL) - isSheet [implementation]
(BOOL) - becomesKeyOnlyIfNeeded [implementation]
(BOOL) - worksWhenModal [implementation]
(void) - performKeyEquivalent: [implementation]
(void) - keyDown: [implementation]
(void) - insertNewline: [implementation]
(void) - insertTab: [implementation]
(void) - recalculateKeyViewLoop [implementation]
(void) - setAutorecalculatesKeyViewLoop: [implementation]
(BOOL) - autorecalculatesKeyViewLoop [implementation]
(void) - selectNextKeyView: [implementation]
(void) - selectPreviousKeyView: [implementation]
(void) - selectKeyViewFollowingView: [implementation]
(void) - selectKeyViewPrecedingView: [implementation]
(void) - setDefaultButtonCell: [implementation]
(CPButton) - defaultButtonCell [implementation]
(void) - setDefaultButton: [implementation]
(CPButton) - defaultButton [implementation]
(void) - enableKeyEquivalentForDefaultButton [implementation]
(void) - enableKeyEquivalentForDefaultButtonCell [implementation]
(void) - disableKeyEquivalentForDefaultButton [implementation]
(void) - disableKeyEquivalentForDefaultButtonCell [implementation]
Static Public Member Functions
(void) + initialize [implementation]
(CGRect) + frameRectForContentRect:styleMask: [implementation]
Detailed Description
An CPWindow instance represents a window, panel or menu on the screen.
Each window has a style, which determines how the window is decorated; whether it has a border, a title bar, a resize bar, minimise and close buttons.
A window has a frame. This is the frame of the entire window on the screen, including all decorations and borders. The origin of the frame represents its bottom left corner and the frame is expressed in screen coordinates.
A window always contains a content view which is the highest level view available for public (application) use. This view fills the area of the window inside any decoration/border. This is the only part of the window that application programmers are allowed to draw in directly.
You can convert between view coordinates and window base coordinates using the [CPView -convertPoint:fromView:], [CPView -convertPoint:toView:], [CPView -convertRect:fromView:], and [CPView -convertRect:toView:] methods with a nil view argument.
Delegate Methods
-(void)windowDidResize:(CPNotification)notification; Sent from the notification center when the window has been resized.
Parameters:
notification contains information about the resize event
-(CPUndoManager)windowWillReturnUndoManager:(CPWindow)window; Called to obtain the undo manager for a window
Parameters:
window the window for which to return the undo manager
Returns:
the window's undo manager
-(void)windowDidBecomeMain:(CPNotification)notification; Sent from the notification center when the delegate's window becomes the main window.
Parameters:
notification contains information about the event
-(void)windowDidResignMain:(CPNotification)notification; Sent from the notification center when the delegate's window has resigned main window status.
Parameters:
notification contains information about the event
-(void)windowDidResignKey:(CPNotification)notification; Sent from the notification center when the delegate's window has resigned key window status.
Parameters:
notification contains information about the event
-(BOOL)windowShouldClose:(id)window; Called when the user tries to close the window.
Parameters:
window the window to close
Returns:
YES allows the window to close. NO vetoes the close operation and leaves the window open.
Definition at line 406 of file CPDragServer.j.
Member Function Documentation
- (BOOL) acceptsFirstResponder [implementation]
Definition at line 1132 of file CPWindow.j.
- (BOOL) acceptsMouseMovedEvents [implementation]
Definition at line 1172 of file CPWindow.j.
- (void) animationDidEnd: (id) anim [implementation]
Definition at line 1974 of file CPWindow.j.
References CPNotificationCenter::defaultCenter, and CPNotificationCenter::postNotificationName:object:.
- (CPWindow) attachedSheet [implementation]
Returns the window's attached sheet.
Definition at line 2043 of file CPWindow.j.
- (BOOL) autorecalculatesKeyViewLoop [implementation]
Definition at line 2164 of file CPWindow.j.
- (void) awakeFromCib [implementation]
Definition at line 471 of file CPWindow.j.
References makeFirstResponder:.
- (CPColor) backgroundColor [implementation]
Returns the window's background color.
Definition at line 883 of file CPWindow.j.
- (void) becomeKeyWindow [implementation]
Called when the receiver should become the key window. It also sends the -becomeKeyWindow message to the first responder.
Definition at line 1412 of file CPWindow.j.
Referenced by makeKeyWindow.
- (void) becomeMainWindow [implementation]
Called to tell the receiver that it has become the main window.
Definition at line 1808 of file CPWindow.j.
References CPNotificationCenter::defaultCenter, and CPNotificationCenter::postNotificationName:object:.
Referenced by makeMainWindow.
- (BOOL) becomesKeyOnlyIfNeeded [implementation]
Definition at line 2064 of file CPWindow.j.
- (BOOL) canBecomeKeyWindow [implementation]
Determines if the window can become the key window.
Returns:
YES means the window can become the key window.
Definition at line 1422 of file CPWindow.j.
- (BOOL) canBecomeMainWindow [implementation]
Returns YES if the window can become the main window.
Definition at line 1781 of file CPWindow.j.
- (void) center [implementation]
Sets the window location to be the center of the screen
Definition at line 1283 of file CPWindow.j.
References frame, CPPlatform::isBrowser, screen, setFrameOrigin:, and size.
- (void) close [implementation]
Closes the window. Posts a CPWindowWillCloseNotification to the notification center before closing the window.
Definition at line 1762 of file CPWindow.j.
References CPNotificationCenter::defaultCenter, orderOut:, and CPNotificationCenter::postNotificationName:object:.
Referenced by CPWindowController::close, and performClose:.
- (CGRect) contentRectForFrameRect: (CGRect) aFrame [implementation]
Returns the receiver's content rectangle. A content rectangle does not include toolbars.
Parameters:
aFrame the window's frame rectangle
Definition at line 587 of file CPWindow.j.
Referenced by setContentView:.
- (CPView) contentView [implementation]
Returns the window's current content view.
Definition at line 866 of file CPWindow.j.
Referenced by performKeyEquivalent:, and CPWindowController::setViewController:.
- (CPButton) defaultButton [implementation]
Definition at line 2216 of file CPWindow.j.
Referenced by defaultButtonCell.
- (CPButton) defaultButtonCell [implementation]
Definition at line 2202 of file CPWindow.j.
References defaultButton.
- (id) delegate [implementation]
Returns window's delegate
Definition at line 1102 of file CPWindow.j.
- (void) deminiaturize: (id) sender [implementation]
Restores a mimized window to it's original size.
Definition at line 1668 of file CPWindow.j.
References CPNotificationCenter::defaultCenter, CPPlatformWindow::deminiaturize:, platformWindow, and CPNotificationCenter::postNotificationName:object:.
- (void) disableKeyEquivalentForDefaultButton [implementation]
Definition at line 2231 of file CPWindow.j.
Referenced by disableKeyEquivalentForDefaultButtonCell.
- (void) disableKeyEquivalentForDefaultButtonCell [implementation]
Definition at line 2236 of file CPWindow.j.
References disableKeyEquivalentForDefaultButton.
- (void) doCommandBySelector: (SEL) aSelector [implementation]
Definition at line 1124 of file CPWindow.j.
- (void) dragImage: (CPImage) anImage at: (CGPoint) imageLocation offset: (CGSize) mouseOffset event: (CPEvent) anEvent pasteboard: (CPPasteboard) aPasteboard source: (id) aSourceObject slideBack: (BOOL) slideBack [implementation]
Initiates a drag operation from the receiver to another view that accepts dragged data.
Parameters:
anImage the image to be dragged
aLocation the lower-left corner coordinate of anImage
mouseOffset the distance from the -mouseDown: location and the current location
anEvent the -mouseDown: that triggered the drag
aPastebaord the pasteboard that holds the drag data
aSourceObject the drag operation controller
slideBack Whether the image should 'slide back' if the drag is rejected
Definition at line 1484 of file CPWindow.j.
References CPDragServer::dragImage:fromWindow:at:offset:event:pasteboard:source:slideBack:, and CPDragServer::sharedDragServer.
- (void) dragView: (CPView) aView at: (CGPoint) viewLocation offset: (CGSize) mouseOffset event: (CPEvent) anEvent pasteboard: (CPPasteboard) aPasteboard source: (id) aSourceObject slideBack: (BOOL) slideBack [implementation]
Initiates a drag operation from the receiver to another view that accepts dragged data.
Parameters:
aView the view to be dragged
aLocation the lower-left corner coordinate of aView
mouseOffset the distance from the -mouseDown: location and the current location
anEvent the -mouseDown: that triggered the drag
aPastebaord the pasteboard that holds the drag data
aSourceObject the drag operation controller
slideBack Whether the view should 'slide back' if the drag is rejected
Definition at line 1521 of file CPWindow.j.
References CPDragServer::dragView:fromWindow:at:offset:event:pasteboard:source:slideBack:, and CPDragServer::sharedDragServer.
- (void) enableKeyEquivalentForDefaultButton [implementation]
Definition at line 2221 of file CPWindow.j.
Referenced by enableKeyEquivalentForDefaultButtonCell.
- (void) enableKeyEquivalentForDefaultButtonCell [implementation]
Definition at line 2226 of file CPWindow.j.
References enableKeyEquivalentForDefaultButton.
- (CPResponder) firstResponder [implementation]
Returns the window's current first responder.
Definition at line 1167 of file CPWindow.j.
Referenced by sendEvent:.
- (CGRect) frame [implementation]
Returns the window's frame rectangle
Definition at line 605 of file CPWindow.j.
Referenced by center.
- (CGRect) frameRectForContentRect: (CGRect) aContentRect [implementation]
Retrieves the frame rectangle for this window.
Parameters:
aContentRect the window's content rectangle
Returns:
the window's frame rectangle
Definition at line 597 of file CPWindow.j.
+ (CGRect) frameRectForContentRect: (CGRect) aContentRect styleMask: (unsigned) aStyleMask [implementation]
Returns the frame rectangle used by a window.
Parameters:
aContentRect the content rectangle of the window
aStyleMask the style mask of the window
Returns:
the matching window's frame rectangle
Definition at line 578 of file CPWindow.j.
- (BOOL) hasShadow [implementation]
Returns YES if the window has a drop shadow. NO otherwise.
Definition at line 970 of file CPWindow.j.
- (BOOL) ignoresMouseEvents [implementation]
Definition at line 1182 of file CPWindow.j.
- (id) init [implementation]
Definition at line 337 of file CPWindow.j.
References initWithContentRect:styleMask:.
+ (void) initialize [implementation]
Definition at line 327 of file CPWindow.j.
References CPBundle::bundleForClass:, and CPWindowSavingImage.
- (id) initWithContentRect: (CGRect) aContentRect styleMask: (unsigned int) aStyleMask [implementation]
Initializes the window. The method also takes a style bit mask made up of any of the following values:
CPBorderlessWindowMask
CPTitledWindowMask
CPClosableWindowMask
CPMiniaturizableWindowMask
CPResizableWindowMask
CPTexturedBackgroundWindowMask
Parameters:
aContentRect the size and location of the window in screen space
aStyleMask a style mask
Returns:
the initialized window
Definition at line 357 of file CPWindow.j.
References CGSizeMake(), CPApp, CPBorderlessBridgeWindowMask, CPDOMDisplayServerAppendChild, CPDOMDisplayServerSetStyleLeftTop, CPDOMDisplayServerSetStyleSize, CPPlatform::isBrowser, platformWindow, CPPlatformWindow::primaryPlatformWindow, CPSet::set, setContentView:, setFullPlatformWindow:, setHasShadow:, setLevel:, setMovableByWindowBackground:, setPlatformWindow:, and setShowsResizeIndicator:.
Referenced by init.
- (void) insertNewline: (id) sender [implementation]
Definition at line 2093 of file CPWindow.j.
- (void) insertTab: (id) sender [implementation]
Definition at line 2099 of file CPWindow.j.
References selectNextKeyView:.
- (BOOL) isDocumentEdited [implementation]
Returns YES if the document has been edited.
Definition at line 1586 of file CPWindow.j.
- (BOOL) isDocumentSaving [implementation]
Definition at line 1603 of file CPWindow.j.
- (BOOL) isFullPlatformWindow [implementation]
Definition at line 559 of file CPWindow.j.
- (BOOL) isKeyWindow [implementation]
Returns YES if the window is the key window.
Definition at line 1430 of file CPWindow.j.
- (BOOL) isMainWindow [implementation]
Returns YES if this the main window.
Definition at line 1773 of file CPWindow.j.
- (void) isMiniaturized [implementation]
Returns YES if the window is minimized.
Definition at line 1680 of file CPWindow.j.
- (BOOL) isMovableByWindowBackground [implementation]
Returns YES if the window can be moved by dragging its background.
Definition at line 1275 of file CPWindow.j.
- (BOOL) isSheet [implementation]
Returns YES if the window has ever run as a sheet.
Definition at line 2054 of file CPWindow.j.
- (BOOL) isVisible [implementation]
Returns YES if the window is visible. It does not mean that the window is not obscured by other windows.
Definition at line 799 of file CPWindow.j.
- (void) keyDown: (CPEvent) anEvent [implementation]
Definition at line 2085 of file CPWindow.j.
- (int) level [implementation]
Returns the window's current level
Definition at line 791 of file CPWindow.j.
Referenced by CPPlatformWindow::order:window:relativeTo:.
- (void) makeFirstResponder: (CPResponder) aResponder [implementation]
Attempts to make the aResponder the first responder. Before trying to make it the first responder, the receiver will ask the current first responder to resign its first responder status. If it resigns, it will ask aResponder accept first responder, then finally tell it to become first responder.
Returns:
YES if the attempt was successful. NO otherwise.
Definition at line 1144 of file CPWindow.j.
Referenced by awakeFromCib, selectKeyViewFollowingView:, selectKeyViewPrecedingView:, and sendEvent:.
- (void) makeKeyAndOrderFront: (id) aSender [implementation]
Makes the window the key window and brings it to the front of the screen list.
Parameters:
aSender the object requesting this
Definition at line 1439 of file CPWindow.j.
References makeKeyWindow, makeMainWindow, and orderFront:.
Referenced by sendEvent:.
- (void) makeKeyWindow [implementation]
Makes this window the key window.
Definition at line 1450 of file CPWindow.j.
References becomeKeyWindow, and CPApp.
Referenced by makeKeyAndOrderFront:.
- (void) makeMainWindow [implementation]
Makes the receiver the main window.
Definition at line 1793 of file CPWindow.j.
References becomeMainWindow, and CPApp.
Referenced by makeKeyAndOrderFront:.
- (CGSize) maxSize [implementation]
Returns the window's maximum size.
Definition at line 962 of file CPWindow.j.
- (void) miniaturize: (id) sender [implementation]
Minimizes the window. Posts a CPWindowWillMiniaturizeNotification to the notification center before minimizing the window.
Definition at line 1654 of file CPWindow.j.
References CPNotificationCenter::defaultCenter, CPPlatformWindow::miniaturize:, platformWindow, and CPNotificationCenter::postNotificationName:object:.
Referenced by performMiniaturize:.
- (CGSize) minSize [implementation]
Returns the windows minimum size.
Definition at line 922 of file CPWindow.j.
- (void) orderBack: (id) aSender [implementation]
Definition at line 739 of file CPWindow.j.
- (void) orderFront: (id) aSender [implementation]
Makes the receiver the front most window in the screen ordering.
Parameters:
aSender the object that requested this
Definition at line 728 of file CPWindow.j.
Referenced by makeKeyAndOrderFront:.
- (void) orderOut: (id) aSender [implementation]
Hides the window.
Parameters:
the object that requested this
Definition at line 748 of file CPWindow.j.
References CPApp, and resignKeyWindow.
Referenced by close, and CPView::exitFullScreenModeWithOptions:.
- (void) orderWindow: (CPWindowOrderingMode) aPlace relativeTo: (int) otherWindowNumber [implementation]
Relocates the window in the screen list.
Parameters:
aPlace the positioning relative to otherWindowNumber
otherWindowNumber the window relative to which the receiver should be placed
Definition at line 771 of file CPWindow.j.
- (void) performClose: (id) aSender [implementation]
Simulates the user closing the window, then closes the window.
Parameters:
aSender the object making this request
Definition at line 1691 of file CPWindow.j.
References close, CPClosableWindowMask, CPKeyDown, and platformWindow.
- (void) performKeyEquivalent: (CPEvent) anEvent [implementation]
Definition at line 2078 of file CPWindow.j.
References contentView, and CPView::performKeyEquivalent:.
- (void) performMiniaturize: (id) aSender [implementation]
Simulates the user minimizing the window, then minimizes the window.
Parameters:
aSender the object making this request
Definition at line 1644 of file CPWindow.j.
References miniaturize:.
- (CPPlatformWindow) platformWindow [implementation]
Definition at line 438 of file CPWindow.j.
Referenced by deminiaturize:, CPDragServer::dragView:fromWindow:at:offset:event:pasteboard:source:slideBack:, initWithContentRect:styleMask:, miniaturize:, performClose:, CPApplication::sendEvent:, setShadowStyle:, and CPApplication::terminate:.
- (void) recalculateKeyViewLoop [implementation]
Definition at line 2125 of file CPWindow.j.
- (CPArray) registeredDraggedTypes [implementation]
Returns an array of all types the receiver accepts for dragging operations.
Returns:
an array of CPPasteBoards
Definition at line 1546 of file CPWindow.j.
- (void) registerForDraggedTypes: (CPArray) pasteboardTypes [implementation]
Sets the receiver's list of acceptable data types for a dragging operation.
Parameters:
pasteboardTypes an array of CPPasteboards
Definition at line 1530 of file CPWindow.j.
- (CPString) representedFilename [implementation]
Returns the path to the file the receiver represents
Definition at line 1235 of file CPWindow.j.
- (CPURL) representedURL [implementation]
Returns the URL that the receiver represents
Definition at line 1251 of file CPWindow.j.
- (void) resignKeyWindow [implementation]
Causes the window to resign it's key window status.
Definition at line 1465 of file CPWindow.j.
Referenced by orderOut:.
- (void) resignMainWindow [implementation]
Called when the window resigns main window status.
Definition at line 1821 of file CPWindow.j.
References CPNotificationCenter::defaultCenter, and CPNotificationCenter::postNotificationName:object:.
- (CGSize) resizeIndicatorOffset [implementation]
Returns the offset of the window's resize indicator.
Definition at line 830 of file CPWindow.j.
- (CPScreen) screen [implementation]
Definition at line 1256 of file CPWindow.j.
Referenced by center.
- (void) selectKeyViewFollowingView: (CPView) aView [implementation]
Definition at line 2181 of file CPWindow.j.
References makeFirstResponder:, and CPView::nextValidKeyView.
- (void) selectKeyViewPrecedingView: (CPView) aView [implementation]
Definition at line 2189 of file CPWindow.j.
References makeFirstResponder:, and CPView::previousValidKeyView.
- (void) selectNextKeyView: (id) sender [implementation]
Definition at line 2169 of file CPWindow.j.
Referenced by insertTab:.
- (void) selectPreviousKeyView: (id) sender [implementation]
Definition at line 2175 of file CPWindow.j.
- (void) sendEvent: (CPEvent) anEvent [implementation]
Dispatches events that are sent to it from CPApplication.
Parameters:
anEvent the event to be dispatched
Definition at line 1295 of file CPWindow.j.
References CPKeyDown, CPKeyUp, CPLeftMouseDown, CPLeftMouseDragged, CPLeftMouseUp, CPMouseMoved, CPRightMouseDown, CPRightMouseDragged, CPRightMouseUp, CPScrollWheel, firstResponder, CPResponder::keyDown:, CPResponder::keyUp:, CPEvent::locationInWindow, makeFirstResponder:, makeKeyAndOrderFront:, MIN, CPEvent::modifierFlags, CPEvent::mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:, CPEvent::timestamp, CPEvent::type, and CPEvent::window.
Referenced by CPApplication::sendEvent:.
- (void) setAcceptsMouseMovedEvents: (BOOL) shouldAcceptMouseMovedEvents [implementation]
Definition at line 1177 of file CPWindow.j.
- (void) setAutorecalculatesKeyViewLoop: (BOOL) shouldRecalculate [implementation]
Definition at line 2151 of file CPWindow.j.
- (void) setBackgroundColor: (CPColor) aColor [implementation]
Sets the window's background color.
Parameters:
aColor the new color for the background
Definition at line 875 of file CPWindow.j.
- (void) setContentView: (CPView) aView [implementation]
Sets the window's content view. The new view will be resized to fit inside the content rectangle of the window.
Parameters:
aView the new content view for the receiver
Definition at line 849 of file CPWindow.j.
References CGRectGetHeight(), CGRectGetWidth(), CGRectMake(), and contentRectForFrameRect:.
Referenced by initWithContentRect:styleMask:.
- (void) setDefaultButton: (CPButton) aButton [implementation]
Definition at line 2207 of file CPWindow.j.
Referenced by setDefaultButtonCell:.
- (void) setDefaultButtonCell: (CPButton) aButton [implementation]
Definition at line 2197 of file CPWindow.j.
References setDefaultButton:.
- (void) setDelegate: (id) aDelegate [implementation]
Sets the delegate for the window. Passing nil will just remove the window's current delegate.
Parameters:
aDelegate an object to respond to the various delegate methods of CPWindow
Definition at line 1060 of file CPWindow.j.
References CPNotificationCenter::defaultCenter.
- (void) setDocumentEdited: (BOOL) isDocumentEdited [implementation]
Sets whether the document has been edited.
Parameters:
isDocumentEdited YES if the document has been edited.
Definition at line 1571 of file CPWindow.j.
Referenced by CPWindowController::setDocumentEdited:.
- (void) setDocumentSaving: (BOOL) isDocumentSaving [implementation]
Definition at line 1591 of file CPWindow.j.
- (void) setFrame: (CGRect) aFrame [implementation]
Sets the window's frame rectangle
Definition at line 701 of file CPWindow.j.
References setFrame:display:animate:.
Referenced by CPDOMWindowLayer::insertWindow:atIndex:, and setFullPlatformWindow:.
- (void) setFrame: (CGRect) aFrame display: (BOOL) shouldDisplay [implementation]
Definition at line 693 of file CPWindow.j.
- (void) setFrame: (CGRect) aFrame display: (BOOL) shouldDisplay animate: (BOOL) shouldAnimate [implementation]
Sets the window's frame rectangle. Also tells the window whether it should animate the resize operation, and redraw itself if necessary.
Parameters:
aFrame the new size and location for the window
shouldDisplay whether the window should redraw its views
shouldAnimate whether the window resize should be animated
Definition at line 617 of file CPWindow.j.
References CPDOMDisplayServerSetStyleLeftTop, CPNotificationCenter::defaultCenter, MAX, MIN, CPNotificationCenter::postNotificationName:object:, and size.
Referenced by setFrame:, setFrameOrigin:, and setFrameSize:.
- (void) setFrameOrigin: (CGPoint) anOrigin [implementation]
Sets the window's location.
Parameters:
anOrigin the new location for the window
Definition at line 710 of file CPWindow.j.
References setFrame:display:animate:.
Referenced by center.
- (void) setFrameSize: (CGSize) aSize [implementation]
Sets the window's size.
Parameters:
aSize the new size for the window
Definition at line 719 of file CPWindow.j.
References setFrame:display:animate:.
Referenced by setMaxSize:, and setMinSize:.
- (void) setFullPlatformWindow: (BOOL) shouldBeFullPlatformWindow [implementation]
Definition at line 519 of file CPWindow.j.
References frame, setFrame:, setHasShadow:, and setLevel:.
Referenced by initWithContentRect:styleMask:.
- (void) setHasShadow: (BOOL) shouldHaveShadow [implementation]
Sets whether the window should have a drop shadow.
Parameters:
shouldHaveShadow YES to have a drop shadow.
Definition at line 1039 of file CPWindow.j.
Referenced by initWithContentRect:styleMask:, and setFullPlatformWindow:.
- (void) setIgnoresMouseEvents: (BOOL) shouldIgnoreMouseEvents [implementation]
Definition at line 1187 of file CPWindow.j.
- (void) setLevel: (int) aLevel [implementation]
Sets the window's level
Parameters:
the window's new level
Definition at line 780 of file CPWindow.j.
Referenced by initWithContentRect:styleMask:, and setFullPlatformWindow:.
- (void) setMaxSize: (CGSize) aSize [implementation]
Sets the window's maximum size. If the provided size is the same as the current maximum size, the method simply returns.
Parameters:
aSize the new maximum size
Definition at line 933 of file CPWindow.j.
References CGSizeCreateCopy(), CGSizeEqualToSize(), CGSizeMakeCopy(), frame, setFrameSize:, and size.
- (void) setMinSize: (CGSize) aSize [implementation]
Sets the window's minimum size. If the provided size is the same as the current minimum size, the method simply returns. the new minimum size for the window
Definition at line 893 of file CPWindow.j.
References CGSizeCreateCopy(), CGSizeEqualToSize(), CGSizeMakeCopy(), frame, setFrameSize:, and size.
- (void) setMovableByWindowBackground: (BOOL) shouldBeMovableByWindowBackground [implementation]
Sets whether the window can be moved by dragging its background. The default is based on the window style.
Parameters:
shouldBeMovableByWindowBackground YES makes the window move from a background drag.
Definition at line 1267 of file CPWindow.j.
Referenced by initWithContentRect:styleMask:.
- (void) setPlatformWindow: (CPPlatformWindow) aPlatformWindow [implementation]
Definition at line 443 of file CPWindow.j.
Referenced by initWithContentRect:styleMask:.
- (void) setRepresentedFilename: (CPString) aFilePath [implementation]
Sets the path to the file the receiver represents
Definition at line 1226 of file CPWindow.j.
References setRepresentedURL:.
Referenced by setTitleWithRepresentedFilename:.
- (void) setRepresentedURL: (CPURL) aURL [implementation]
Sets the URL that the receiver represents
Definition at line 1243 of file CPWindow.j.
Referenced by setRepresentedFilename:.
- (void) setResizeIndicatorOffset: (CGSize) anOffset [implementation]
Sets the offset of the window's resize indicator.
Parameters:
aSize the offset for the resize indicator
Definition at line 839 of file CPWindow.j.
- (void) setShadowStyle: (unsigned) aStyle [implementation]
Definition at line 1049 of file CPWindow.j.
References platformWindow, and CPPlatformWindow::setShadowStyle:.
- (void) setShowsResizeIndicator: (BOOL) shouldShowResizeIndicator [implementation]
Sets the window's resize indicator.
Parameters:
shouldShowResizeIndicator YES sets the window to show its resize indicator.
Definition at line 816 of file CPWindow.j.
References showsResizeIndicator.
Referenced by initWithContentRect:styleMask:.
- (void) setTitle: (CPString) aTitle [implementation]
Sets the window's title bar string
Definition at line 1205 of file CPWindow.j.
Referenced by setTitleWithRepresentedFilename:.
- (void) setTitleWithRepresentedFilename: (CPString) aFilePath [implementation]
Sets the title bar to represent a file path
Definition at line 1217 of file CPWindow.j.
References CPString::lastPathComponent, setRepresentedFilename:, and setTitle:.
- (void) setToolbar: (CPToolbar) aToolbar [implementation]
Sets the window's toolbar.
Parameters:
aToolbar the window's new toolbar
Definition at line 1841 of file CPWindow.j.
- (void) setWindowController: (CPWindowController) aWindowController [implementation]
Sets the window's controller
Parameters:
aWindowController a window controller
Definition at line 1111 of file CPWindow.j.
- (BOOL) showsResizeIndicator [implementation]
Returns YES if the window's resize indicator is showing. NO otherwise.
Definition at line 807 of file CPWindow.j.
Referenced by setShowsResizeIndicator:.
- (unsigned) styleMask [implementation]
Returns the window's style mask.
Definition at line 567 of file CPWindow.j.
Referenced by CPApplication::beginSheet:modalForWindow:modalDelegate:didEndSelector:contextInfo:.
- (CPString) title [implementation]
Returns the window's title bar string
Definition at line 1197 of file CPWindow.j.
- (void) toggleToolbarShown: (id) aSender [implementation]
Definition at line 1860 of file CPWindow.j.
References CPToolbar::isVisible, CPToolbar::setVisible:, and toolbar.
- (CPToolbar) toolbar [implementation]
Return's the window's toolbar
Definition at line 1832 of file CPWindow.j.
Referenced by toggleToolbarShown:.
- (void) unregisterDraggedTypes [implementation]
Resets the array of acceptable data types for a dragging operation.
Definition at line 1557 of file CPWindow.j.
References CPSet::set.
- (CPWindowController) windowController [implementation]
Returns the window's controller.
Definition at line 1119 of file CPWindow.j.
- (int) windowNumber [implementation]
Returns the window's number in the desktop's screen list
Definition at line 1403 of file CPWindow.j.
- (BOOL) worksWhenModal [implementation]
Returns YES if the receiver is able to receive input events even when a modal session is active.
Definition at line 2073 of file CPWindow.j.
The documentation for this class was generated from the following files:
AppKit/CPDragServer.j
AppKit/CPWindow/CPWindow.j