Cappuccino: CPIndexSet Class Reference
CPIndexSet Class Reference
[Foundation]
A collection of unique integers.
Public Member Functions
(id) - init [implementation]
(id) - initWithIndex: [implementation]
(id) - initWithIndexesInRange: [implementation]
(id) - initWithIndexSet: [implementation]
(BOOL) - isEqualToIndexSet: [implementation]
(BOOL) - containsIndex: [implementation]
(BOOL) - containsIndexesInRange: [implementation]
(BOOL) - containsIndexes: [implementation]
(BOOL) - intersectsIndexesInRange: [implementation]
(int) - count [implementation]
(CPInteger) - firstIndex [implementation]
(CPInteger) - lastIndex [implementation]
(CPInteger) - indexGreaterThanIndex: [implementation]
(CPInteger) - indexLessThanIndex: [implementation]
(CPInteger) - indexGreaterThanOrEqualToIndex: [implementation]
(CPInteger) - indexLessThanOrEqualToIndex: [implementation]
(CPInteger) - getIndexes:maxCount:inIndexRange: [implementation]
(CPString) - description [implementation]
(id) - initWithCoder: [implementation]
(void) - encodeWithCoder: [implementation]
(id) - copy [implementation]
(id) - mutableCopy [implementation]
(void) - addIndex: [implementation]
(void) - addIndexes: [implementation]
(void) - addIndexesInRange: [implementation]
(void) - removeIndex: [implementation]
(void) - removeIndexes: [implementation]
(void) - removeAllIndexes [implementation]
(void) - removeIndexesInRange: [implementation]
(void) - shiftIndexesStartingAtIndex:by: [implementation]
Static Public Member Functions
(id) + indexSet [implementation]
(id) + indexSetWithIndex: [implementation]
(id) + indexSetWithIndexesInRange: [implementation]
Detailed Description
A collection of unique integers.
Instances of this class are collections of numbers. Each integer can appear in a collection only once.
Definition at line 38 of file CPIndexSet.j.
Member Function Documentation
- (void) addIndex: (CPInteger) anIndex [implementation]
Adds an index to the set.
Parameters:
anIndex the index to add
Definition at line 476 of file CPIndexSet.j.
References addIndexesInRange:.
- (void) addIndexes: (CPIndexSet) anIndexSet [implementation]
Adds indices to the set
Parameters:
anIndexSet a set of indices to add to the receiver
Definition at line 485 of file CPIndexSet.j.
References addIndexesInRange:.
- (void) addIndexesInRange: (CPRange) aRange [implementation]
Adds the range of indices to the set
Parameters:
aRange the range of numbers to add as indices to the set
Definition at line 499 of file CPIndexSet.j.
References CPMaxRange(), and CPUnionRange().
Referenced by addIndex:, addIndexes:, and shiftIndexesStartingAtIndex:by:.
- (BOOL) containsIndex: (CPInteger) anIndex [implementation]
Returns YES if the index set contains the specified index.
Parameters:
anIndex the index to check for in the set
Returns:
YES if anIndex is in the receiver index set
Definition at line 167 of file CPIndexSet.j.
References CPNotFound.
- (BOOL) containsIndexes: (CPIndexSet) anIndexSet [implementation]
Returns YES if the receving index set contains all the indices in the argument.
Parameters:
anIndexSet the set of indices to check for in the receiving index set
Definition at line 202 of file CPIndexSet.j.
- (BOOL) containsIndexesInRange: (CPRange) aRange [implementation]
Returns YES if the index set contains all the numbers in the specified range.
Parameters:
aRange the range of numbers to check for in the index set
Definition at line 176 of file CPIndexSet.j.
References CPIntersectionRange(), and CPNotFound.
- (id) copy [implementation]
Creates a deep copy of the index set. The returned copy is mutable. The reason for the two copy methods is for source compatability with GNUStep code.
Returns:
the index set copy
Definition at line 819 of file CPIndexSet.j.
- (int) count [implementation]
The number of indices in the set
Definition at line 249 of file CPIndexSet.j.
Referenced by encodeWithCoder:, initWithCoder:, initWithIndexSet:, CPArray::insertObjects:atIndexes:, and shiftIndexesStartingAtIndex:by:.
- (CPString) description [implementation]
Definition at line 429 of file CPIndexSet.j.
References CPMaxRange().
- (void) encodeWithCoder: (CPCoder) aCoder [implementation]
Writes out the index set to the specified coder.
Parameters:
aCoder the coder to which the index set will be written
Definition at line 795 of file CPIndexSet.j.
References count, and CPStringFromRange().
- (CPInteger) firstIndex [implementation]
Return the first index in the set
Definition at line 258 of file CPIndexSet.j.
References CPNotFound.
Referenced by getIndexes:maxCount:inIndexRange:, CPArray::insertObjects:atIndexes:, and CPArray::replaceObjectsAtIndexes:withObjects:.
- (CPInteger) getIndexes: (CPArray) anArray maxCount: (CPInteger) aMaxCount inIndexRange: (CPRange) aRange [implementation]
Fills up the specified array with numbers from the index set within the specified range. The method stops filling up the array until the aMaxCount number have been added or the range maximum is reached.
Parameters:
anArray the array to fill up
aMaxCount the maximum number of numbers to adds
aRangePointer the range of indices to add
Returns:
the number of elements added to the array
Definition at line 366 of file CPIndexSet.j.
References CPNotFound, firstIndex, lastIndex, MAX, and MIN.
- (CPInteger) indexGreaterThanIndex: (CPInteger) anIndex [implementation]
Returns the first index value in the receiver which is greater than anIndex.
Returns:
the closest index or CPNotFound if no match was found
Definition at line 281 of file CPIndexSet.j.
References CPLocationInRange(), and CPNotFound.
Referenced by indexGreaterThanOrEqualToIndex:, CPArray::insertObjects:atIndexes:, and CPArray::replaceObjectsAtIndexes:withObjects:.
- (CPInteger) indexGreaterThanOrEqualToIndex: (CPInteger) anIndex [implementation]
Returns the first index value in the receiver which is greater than or equal to anIndex.
Returns:
the matching index or CPNotFound if no match was found
Definition at line 343 of file CPIndexSet.j.
References indexGreaterThanIndex:.
- (CPInteger) indexLessThanIndex: (CPInteger) anIndex [implementation]
Returns the first index value in the receiver which is less than anIndex.
Returns:
the closest index or CPNotFound if no match was found
Definition at line 312 of file CPIndexSet.j.
References CPLocationInRange(), and CPNotFound.
Referenced by indexLessThanOrEqualToIndex:, and CPArray::removeObjectsAtIndexes:.
- (CPInteger) indexLessThanOrEqualToIndex: (CPInteger) anIndex [implementation]
Returns the first index value in the receiver which is less than or equal to anIndex.
Returns:
the matching index or CPNotFound if no match was found
Definition at line 352 of file CPIndexSet.j.
References indexLessThanIndex:.
+ (id) indexSet [implementation]
Returns a new empty index set.
Definition at line 48 of file CPIndexSet.j.
Referenced by CPCollectionView::initWithCoder:, CPCollectionView::initWithFrame:, CPAccordionView::initWithFrame:, and CPCollectionView::mouseDown:.
+ (id) indexSetWithIndex: (int) anIndex [implementation]
Returns a new index set with just one index.
Definition at line 56 of file CPIndexSet.j.
Referenced by CPCollectionView::mouseDown:.
+ (id) indexSetWithIndexesInRange: (CPRange) aRange [implementation]
Returns a new index set with all the numbers in the specified range.
Parameters:
aRange the range of numbers to add to the index set.
Definition at line 65 of file CPIndexSet.j.
Referenced by CPAccordionView::collapsedItemIndexes.
- (id) init [implementation]
Definition at line 72 of file CPIndexSet.j.
References initWithIndexesInRange:.
- (id) initWithCoder: (CPCoder) aCoder [implementation]
Initializes the index set from a coder.
Parameters:
aCoder the coder from which to read the index set data
Returns:
the initialized index set
Definition at line 770 of file CPIndexSet.j.
References count, and CPRangeFromString().
- (id) initWithIndex: (CPInteger) anIndex [implementation]
Initializes the index set with a single index.
Returns:
the initialized index set
Definition at line 81 of file CPIndexSet.j.
References initWithIndexesInRange:.
- (id) initWithIndexesInRange: (CPRange) aRange [implementation]
Initializes the index set with numbers from the specified range.
Parameters:
aRange the range of numbers to add to the index set
Returns:
the initialized index set
Definition at line 91 of file CPIndexSet.j.
References MAX.
Referenced by init, and initWithIndex:.
- (id) initWithIndexSet: (CPIndexSet) anIndexSet [implementation]
Initializes the index set with another index set.
Parameters:
anIndexSet the index set from which to read the initial index set
Returns:
the initialized index set
Definition at line 113 of file CPIndexSet.j.
References count.
- (BOOL) intersectsIndexesInRange: (CPRange) aRange [implementation]
Checks if the receiver contains at least one number in aRange.
Parameters:
aRange the range of numbers to check.
Returns:
YES if the receiving index set contains at least one number in the provided range
Definition at line 228 of file CPIndexSet.j.
- (BOOL) isEqualToIndexSet: (CPIndexSet) anIndexSet [implementation]
Compares the receiver with the provided index set.
Parameters:
anIndexSet the index set to compare to
Returns:
YES if the receiver and the index set are functionally equivalent
Definition at line 138 of file CPIndexSet.j.
References CPEqualRanges().
- (CPInteger) lastIndex [implementation]
Returns the last index in the set
Definition at line 269 of file CPIndexSet.j.
References CPNotFound.
Referenced by getIndexes:maxCount:inIndexRange:, CPArray::insertObjects:atIndexes:, and CPArray::removeObjectsAtIndexes:.
- (id) mutableCopy [implementation]
Creates a deep copy of the index set. The returned copy is mutable. The reason for the two copy methods is for source compatability with GNUStep code.
Returns:
the index set copy
Definition at line 830 of file CPIndexSet.j.
- (void) removeAllIndexes [implementation]
Removes all indices from the set
Definition at line 591 of file CPIndexSet.j.
- (void) removeIndex: (CPInteger) anIndex [implementation]
Removes an index from the set
Parameters:
anIndex the index to remove
Definition at line 568 of file CPIndexSet.j.
References removeIndexesInRange:.
- (void) removeIndexes: (CPIndexSet) anIndexSet [implementation]
Removes the indices from the receiving set.
Parameters:
anIndexSet the set of indices to remove from the receiver
Definition at line 578 of file CPIndexSet.j.
References removeIndexesInRange:.
- (void) removeIndexesInRange: (CPRange) aRange [implementation]
Removes the indices in the range from the set.
Parameters:
aRange the range of indices to remove
Definition at line 602 of file CPIndexSet.j.
References CPMaxRange().
Referenced by removeIndex:, and removeIndexes:.
- (void) shiftIndexesStartingAtIndex: (CPInteger) anIndex by: (int) aDelta [implementation]
Shifts the values of indices left or right by a specified amount.
Parameters:
anIndex the index to start the shifting operation from (inclusive)
aDelta the amount and direction to shift. A positive value shifts to the right. A negative value shifts to the left.
Definition at line 685 of file CPIndexSet.j.
References addIndexesInRange:, count, CPMakeRange(), CPMaxRange(), CPNotFound, and j.
The documentation for this class was generated from the following file:
Foundation/CPIndexSet.j