Cappuccino: CPView Class Reference
CPView Class Reference
[AppKit]
Public Member Functions
(void) - setupViewFlags [implementation]
(id) - init [implementation]
(id) - initWithFrame: [implementation]
(CPView) - superview [implementation]
(CPArray) - subviews [implementation]
(CPWindow) - window [implementation]
(void) - addSubview: [implementation]
(void) - addSubview:positioned:relativeTo: [implementation]
(void) - didAddSubview: [implementation]
(void) - removeFromSuperview [implementation]
(void) - replaceSubview:with: [implementation]
(void) - setSubviews: [implementation]
(BOOL) - isDescendantOf: [implementation]
(void) - viewDidMoveToSuperview [implementation]
(void) - viewDidMoveToWindow [implementation]
(void) - viewWillMoveToSuperview: [implementation]
(void) - viewWillMoveToWindow: [implementation]
(void) - willRemoveSubview: [implementation]
(CPMenuItem) - enclosingMenuItem [implementation]
(void) - setTag: [implementation]
(CPInteger) - tag [implementation]
(void) - viewWithTag: [implementation]
(BOOL) - isFlipped [implementation]
(void) - setFrame: [implementation]
(CGRect) - frame [implementation]
(CGPoint) - frameOrigin [implementation]
(CGSize) - frameSize [implementation]
(void) - setCenter: [implementation]
(CGPoint) - center [implementation]
(void) - setFrameOrigin: [implementation]
(void) - setFrameSize: [implementation]
(void) - setBounds: [implementation]
(CGRect) - bounds [implementation]
(CGPoint) - boundsOrigin [implementation]
(CGSize) - boundsSize [implementation]
(void) - setBoundsOrigin: [implementation]
(void) - setBoundsSize: [implementation]
(void) - resizeWithOldSuperviewSize: [implementation]
(void) - resizeSubviewsWithOldSize: [implementation]
(void) - setAutoresizesSubviews: [implementation]
(BOOL) - autoresizesSubviews [implementation]
(void) - setAutoresizingMask: [implementation]
(unsigned) - autoresizingMask [implementation]
(BOOL) - enterFullScreenMode [implementation]
(BOOL) - enterFullScreenMode:withOptions: [implementation]
(void) - exitFullScreenMode [implementation]
(void) - exitFullScreenModeWithOptions: [implementation]
(BOOL) - isInFullScreenMode [implementation]
(void) - setHidden: [implementation]
(BOOL) - isHidden [implementation]
(void) - setAlphaValue: [implementation]
(float) - alphaValue [implementation]
(BOOL) - isHiddenOrHasHiddenAncestor [implementation]
(BOOL) - acceptsFirstMouse: [implementation]
(BOOL) - hitTests [implementation]
(void) - setHitTests: [implementation]
(CPView) - hitTest: [implementation]
(BOOL) - mouseDownCanMoveWindow [implementation]
(void) - mouseDown: [implementation]
(void) - setBackgroundColor: [implementation]
(CPColor) - backgroundColor [implementation]
(CGPoint) - convertPoint:fromView: [implementation]
(CGPoint) - convertPoint:toView: [implementation]
(CGSize) - convertSize:fromView: [implementation]
(CGSize) - convertSize:toView: [implementation]
(CGRect) - convertRect:fromView: [implementation]
(CGRect) - convertRect:toView: [implementation]
(void) - setPostsFrameChangedNotifications: [implementation]
(BOOL) - postsFrameChangedNotifications [implementation]
(void) - setPostsBoundsChangedNotifications: [implementation]
(BOOL) - postsBoundsChangedNotifications [implementation]
(void) - dragImage:at:offset:event:pasteboard:source:slideBack: [implementation]
(void) - dragView:at:offset:event:pasteboard:source:slideBack: [implementation]
(void) - registerForDraggedTypes: [implementation]
(CPArray) - registeredDraggedTypes [implementation]
(void) - unregisterDraggedTypes [implementation]
(void) - drawRect: [implementation]
(void) - setNeedsDisplay: [implementation]
(void) - setNeedsDisplayInRect: [implementation]
(BOOL) - needsDisplay [implementation]
(void) - displayIfNeeded [implementation]
(void) - display [implementation]
(void) - displayIfNeededInRect: [implementation]
(void) - displayRect: [implementation]
(void) - displayRectIgnoringOpacity:inContext: [implementation]
(void) - viewWillDraw [implementation]
(void) - lockFocus [implementation]
(void) - unlockFocus [implementation]
(void) - setNeedsLayout [implementation]
(void) - layoutIfNeeded [implementation]
(void) - layoutSubviews [implementation]
(BOOL) - isOpaque [implementation]
(CGRect) - visibleRect [implementation]
(void) - scrollPoint: [implementation]
(BOOL) - scrollRectToVisible: [implementation]
(BOOL) - autoscroll: [implementation]
(CGRect) - adjustScroll: [implementation]
(void) - scrollRect:by: [implementation]
(CPScrollView) - enclosingScrollView [implementation]
(void) - scrollClipView:toPoint: [implementation]
(void) - reflectScrolledClipView: [implementation]
(BOOL) - performKeyEquivalent: [implementation]
(BOOL) - canBecomeKeyView [implementation]
(CPView) - nextKeyView [implementation]
(CPView) - nextValidKeyView [implementation]
(CPView) - previousKeyView [implementation]
(CPView) - previousValidKeyView [implementation]
(void) - setNextKeyView: [implementation]
(void) - setLayer: [implementation]
(CALayer) - layer [implementation]
(void) - setWantsLayer: [implementation]
(BOOL) - wantsLayer [implementation]
(unsigned) - themeState [implementation]
(BOOL) - hasThemeState: [implementation]
(BOOL) - setThemeState: [implementation]
(BOOL) - unsetThemeState: [implementation]
(void) - setTheme: [implementation]
(CPTheme) - theme [implementation]
(void) - viewDidChangeTheme [implementation]
(void) - setValue:forThemeAttribute:inState: [implementation]
(void) - setValue:forThemeAttribute: [implementation]
(id) - valueForThemeAttribute:inState: [implementation]
(id) - valueForThemeAttribute: [implementation]
(void) - currentValueForThemeAttribute: [implementation]
(CPView) - createEphemeralSubviewNamed: [implementation]
(CGRect) - rectForEphemeralSubviewNamed: [implementation]
(CPView) - layoutEphemeralSubviewNamed:positioned:relativeToEphemeralSubviewNamed: [implementation]
(id) - initWithCoder: [implementation]
(void) - encodeWithCoder: [implementation]
Static Public Member Functions
(void) + initialize [implementation]
(CPSet) + keyPathsForValuesAffectingFrame [implementation]
(CPSet) + keyPathsForValuesAffectingBounds [implementation]
(CPString) + themeClass [implementation]
(CPDictionary) + themeAttributes [implementation]
Detailed Description
CPView is a class which provides facilities for drawing in a window and receiving events. It is the superclass of many of the visual elements of the GUI.
In order to display itself, a view must be placed in a window (represented by an CPWindow object). Within the window is a hierarchy of CPViews, headed by the window's content view. Every other view in a window is a descendant of this view.
Subclasses can override -drawRect: in order to implement their appearance. Other methods of CPView and CPResponder can also be overridden to handle user generated events.
Definition at line 121 of file CPView.j.
Member Function Documentation
- (BOOL) acceptsFirstMouse: (CPEvent) anEvent [implementation]
Returns whether the receiver should be sent a -mouseDown: message for anEvent.
Returns YES by default.
Returns:
YES, if the view object accepts first mouse-down event. NO, otherwise.
Definition at line 1240 of file CPView.j.
- (void) addSubview: (CPView) aSubview [implementation]
Makes the argument a subview of the receiver.
Parameters:
aSubview the CPView to make a subview
Definition at line 331 of file CPView.j.
Referenced by setSubviews:.
- (void) addSubview: (CPView) aSubview positioned: (CPWindowOrderingMode) anOrderingMode relativeTo: (CPView) anotherView [implementation]
Makes aSubview a subview of the receiver. It is positioned relative to anotherView
Parameters:
aSubview the view to add as a subview
anOrderingMode specifies aSubview's ordering relative to anotherView
anotherView aSubview will be positioned relative to this argument
Definition at line 342 of file CPView.j.
References CPNotFound, and CPWindowAbove.
Referenced by layoutEphemeralSubviewNamed:positioned:relativeToEphemeralSubviewNamed:.
- (CGRect) adjustScroll: (CGRect) proposedVisibleRect [implementation]
Subclasses can override this to modify the visible rectangle after a scrolling operation. The default implementation simply returns the provided rectangle.
Parameters:
proposedVisibleRect the rectangle to alter
Returns:
the same adjusted rectangle
Definition at line 1895 of file CPView.j.
- (float) alphaValue [implementation]
Returns the alpha value of the receiver. Ranges from 0.0 to 1.0, where 0.0 is completely transparent and 1.0 is completely opaque.
Definition at line 1215 of file CPView.j.
- (BOOL) autoresizesSubviews [implementation]
Reports whether the receiver automatically resizes its subviews when its frame size changes.
Returns:
YES means it resizes its subviews on a frame size change.
Definition at line 1042 of file CPView.j.
- (unsigned) autoresizingMask [implementation]
Returns the bit mask options for resizing behavior
Definition at line 1059 of file CPView.j.
Referenced by resizeWithOldSuperviewSize:.
- (BOOL) autoscroll: (CPEvent) anEvent [implementation]
Definition at line 1884 of file CPView.j.
References autoscroll:, and superview.
Referenced by autoscroll:.
- (CPColor) backgroundColor [implementation]
Returns the background color of the receiver
Definition at line 1420 of file CPView.j.
- (CGRect) bounds [implementation]
Returns the receiver's bounds. The bounds define the size and location of the receiver inside its frame.
Definition at line 886 of file CPView.j.
Referenced by setLayer:, and setNeedsDisplay:.
- (CGPoint) boundsOrigin [implementation]
Definition at line 891 of file CPView.j.
- (CGSize) boundsSize [implementation]
Definition at line 896 of file CPView.j.
- (BOOL) canBecomeKeyView [implementation]
Definition at line 1958 of file CPView.j.
References isHiddenOrHasHiddenAncestor.
Referenced by nextValidKeyView, and previousValidKeyView.
- (CGPoint) center [implementation]
Returns the center of the receiver's frame to the provided point. The point is defined in the superview's coordinate system.
Returns:
CGPoint the center point of the receiver's frame
Definition at line 755 of file CPView.j.
References CGPointMake().
- (CGPoint) convertPoint: (CGPoint) aPoint fromView: (CPView) aView [implementation]
Converts aPoint from the coordinate space of aView to the coordinate space of the receiver.
Parameters:
aPoint the point to convert
aView the view space to convert from
Returns:
the converted point
Definition at line 1432 of file CPView.j.
References CGPointApplyAffineTransform().
- (CGPoint) convertPoint: (CGPoint) aPoint toView: (CPView) aView [implementation]
Converts aPoint from the receiver's coordinate space to the coordinate space of aView.
Parameters:
aPoint the point to convert
aView the coordinate space to which the point will be converted
Returns:
the converted point
Definition at line 1443 of file CPView.j.
References CGPointApplyAffineTransform().
Referenced by dragImage:at:offset:event:pasteboard:source:slideBack:, dragView:at:offset:event:pasteboard:source:slideBack:, and scrollPoint:.
- (CGRect) convertRect: (CGRect) aRect fromView: (CPView) aView [implementation]
Converts aRect from aView's coordinate space to the receiver's space.
Parameters:
aRect the rectangle to convert
aView the coordinate space from which to convert
Returns:
the converted rectangle
Definition at line 1476 of file CPView.j.
References CGRectApplyAffineTransform().
- (CGRect) convertRect: (CGRect) aRect toView: (CPView) aView [implementation]
Converts aRect from the receiver's coordinate space to aView's coordinate space.
Parameters:
aRect the rectangle to convert
aView the coordinate space to which the rectangle will be converted
Returns:
the converted rectangle
Definition at line 1487 of file CPView.j.
References CGRectApplyAffineTransform().
- (CGSize) convertSize: (CGSize) aSize fromView: (CPView) aView [implementation]
Convert's aSize from aView's coordinate space to the receiver's coordinate space.
Parameters:
aSize the size to convert
aView the coordinate space to convert from
Returns:
the converted size
Definition at line 1454 of file CPView.j.
References CGSizeApplyAffineTransform().
- (CGSize) convertSize: (CGSize) aSize toView: (CPView) aView [implementation]
Convert's aSize from the receiver's coordinate space to aView's coordinate space.
Parameters:
aSize the size to convert
the coordinate space to which the size will be converted
Returns:
the converted size
Definition at line 1465 of file CPView.j.
References CGSizeApplyAffineTransform().
- (CPView) createEphemeralSubviewNamed: (CPString) aViewName [implementation]
Definition at line 2292 of file CPView.j.
Referenced by layoutEphemeralSubviewNamed:positioned:relativeToEphemeralSubviewNamed:.
- (void) currentValueForThemeAttribute: (CPString) aName [implementation]
Definition at line 2284 of file CPView.j.
References CPException::raise:reason:.
Referenced by setValue:forThemeAttribute:, and setValue:forThemeAttribute:inState:.
- (void) didAddSubview: (CPView) aSubview [implementation]
Called when the receiver has added aSubview to it's child views.
Parameters:
aSubview the view that was added
Definition at line 431 of file CPView.j.
- (void) display [implementation]
Draws the entire area of the receiver as defined by its -bounds.
Definition at line 1688 of file CPView.j.
References displayRect:, and visibleRect.
- (void) displayIfNeeded [implementation]
Displays the receiver and any of its subviews that need to be displayed.
Definition at line 1679 of file CPView.j.
References displayRect:.
- (void) displayIfNeededInRect: (CGRect) aRect [implementation]
Definition at line 1693 of file CPView.j.
References displayRect:.
- (void) displayRect: (CPRect) aRect [implementation]
Draws the receiver into the area defined by aRect.
Parameters:
aRect the area to be drawn
Definition at line 1703 of file CPView.j.
References displayRectIgnoringOpacity:inContext:, and viewWillDraw.
Referenced by display, displayIfNeeded, and displayIfNeededInRect:.
- (void) displayRectIgnoringOpacity: (CGRect) aRect inContext: (CPGraphicsContext) aGraphicsContext [implementation]
Definition at line 1712 of file CPView.j.
References CGContextClearRect(), drawRect:, lockFocus, and unlockFocus.
Referenced by displayRect:.
- (void) dragImage: (CPImage) anImage at: (CGPoint) aLocation offset: (CGSize) mouseOffset event: (CPEvent) anEvent pasteboard: (CPPasteboard) aPasteboard source: (id) aSourceObject slideBack: (BOOL) slideBack [implementation]
Initiates a drag operation from the receiver to another view that accepts dragged data.
Parameters:
anImage the image to be dragged
aLocation the lower-left corner coordinate of anImage
mouseOffset the distance from the -mouseDown: location and the current location
anEvent the -mouseDown: that triggered the drag
aPastebaord the pasteboard that holds the drag data
aSourceObject the drag operation controller
slideBack Whether the image should 'slide back' if the drag is rejected
Definition at line 1570 of file CPView.j.
References convertPoint:toView:.
- (void) dragView: (CPView) aView at: (CPPoint) aLocation offset: (CPSize) mouseOffset event: (CPEvent) anEvent pasteboard: (CPPasteboard) aPasteboard source: (id) aSourceObject slideBack: (BOOL) slideBack [implementation]
Initiates a drag operation from the receiver to another view that accepts dragged data.
Parameters:
aView the view to be dragged
aLocation the top-left corner coordinate of aView
mouseOffset the distance from the -mouseDown: location and the current location
anEvent the -mouseDown: that triggered the drag
aPastebaord the pasteboard that holds the drag data
aSourceObject the drag operation controller
slideBack Whether the view should 'slide back' if the drag is rejected
Definition at line 1585 of file CPView.j.
References convertPoint:toView:.
- (void) drawRect: (CPRect) aRect [implementation]
Draws the receiver into aRect. This method should be overridden by subclasses.
Parameters:
aRect the area that should be drawn into
Definition at line 1635 of file CPView.j.
Referenced by displayRectIgnoringOpacity:inContext:.
- (CPMenuItem) enclosingMenuItem [implementation]
Returns the menu item containing the receiver or one of its ancestor views.
Returns:
a menu item, or nil if the view or one of its ancestors wasn't found
Definition at line 639 of file CPView.j.
- (CPScrollView) enclosingScrollView [implementation]
Returns the CPScrollView containing the receiver.
Returns:
the CPScrollView containing the receiver.
Definition at line 1912 of file CPView.j.
- (void) encodeWithCoder: (CPCoder) aCoder [implementation]
Archives the view to a coder.
Parameters:
aCoder the object into which the view's data will be archived.
Definition at line 2458 of file CPView.j.
References CPThemeAttributeEncode(), CPViewNotSizable, nextKeyView, and previousKeyView.
- (BOOL) enterFullScreenMode [implementation]
Puts the receiver into full screen mode.
Definition at line 1069 of file CPView.j.
References enterFullScreenMode:withOptions:.
- (BOOL) enterFullScreenMode: (CPScreen) aScreen withOptions: (CPDictionary) options [implementation]
Puts the receiver into full screen mode.
Parameters:
aScreen the that should be used
options configuration options
Definition at line 1079 of file CPView.j.
References CPPlatformWindow::contentBounds, CPPlatformWindow::primaryPlatformWindow, setAutoresizingMask:, and setFrame:.
Referenced by enterFullScreenMode.
- (void) exitFullScreenMode [implementation]
The receiver should exit full screen mode.
Definition at line 1108 of file CPView.j.
References exitFullScreenModeWithOptions:.
- (void) exitFullScreenModeWithOptions: (CPDictionary) options [implementation]
The receiver should exit full screen mode.
Parameters:
options configurations options
Definition at line 1117 of file CPView.j.
References CPWindow::orderOut:, setAutoresizingMask:, setFrame:, and window.
Referenced by exitFullScreenMode.
- (CGRect) frame [implementation]
Returns the receiver's frame.
Returns:
a copy of the receiver's frame
Definition at line 724 of file CPView.j.
Referenced by CPBox::boxEnclosingView:, CPDragServer::dragView:fromWindow:at:offset:event:pasteboard:source:slideBack:, CPSplitView::isSubviewCollapsed:, and layoutEphemeralSubviewNamed:positioned:relativeToEphemeralSubviewNamed:.
- (CGPoint) frameOrigin [implementation]
Definition at line 729 of file CPView.j.
- (CGSize) frameSize [implementation]
Definition at line 734 of file CPView.j.
- (BOOL) hasThemeState: (CPThemeState) aState [implementation]
Definition at line 2076 of file CPView.j.
References CPThemeState().
- (CPView) hitTest: (CPPoint) aPoint [implementation]
Tests whether a point is contained within this view, or one of its subviews.
Parameters:
aPoint the point to test
Returns:
returns the containing view, or nil if the point is not contained
Definition at line 1268 of file CPView.j.
References CPRectContainsPoint().
- (BOOL) hitTests [implementation]
Returns whether or not the view responds to hit tests.
Returns:
YES if this view listens to -hitTest messages, NO otherwise.
Definition at line 1249 of file CPView.j.
- (id) init [implementation]
Definition at line 246 of file CPView.j.
References initWithFrame:.
+ (void) initialize [implementation]
Definition at line 196 of file CPView.j.
References CachedNotificationCenter, and CPNotificationCenter::defaultCenter.
- (id) initWithCoder: (CPCoder) aCoder [implementation]
Initializes the view from an archive.
Parameters:
aCoder the coder from which to initialize
Returns:
the initialized view
Definition at line 2365 of file CPView.j.
References CPDOMDisplayServerAppendChild, CPDOMDisplayServerSetStyleLeftTop, CPDOMDisplayServerSetStyleSize, CPThemeAttributeDecode(), CPThemeState(), CPViewIsHiddenKey, CPViewNotSizable, CPViewOpacityKey, CPViewThemeStateKey, CPTheme::defaultTheme, CPString::length, CPSet::set, setAlphaValue:, setBackgroundColor:, setHidden:, setNeedsDisplay:, setNeedsLayout, setupViewFlags, and themeClass.
- (id) initWithFrame: (CGRect) aFrame [implementation]
Initializes the receiver for usage with the specified bounding rectangle
Returns:
the initialized view
Definition at line 255 of file CPView.j.
References CPDOMDisplayServerSetStyleLeftTop, CPDOMDisplayServerSetStyleSize, CPThemeStateNormal, CPViewNotSizable, CPTheme::defaultTheme, height, CPSet::set, setupViewFlags, and width.
Referenced by init.
- (BOOL) isDescendantOf: (CPView) aView [implementation]
Returns YES if the receiver is, or is a descendant of, aView.
Parameters:
aView the view to test for ancestry
Definition at line 582 of file CPView.j.
- (BOOL) isFlipped [implementation]
Returns whether the view is flipped.
Returns:
YES if the view is flipped. NO, otherwise.
Definition at line 692 of file CPView.j.
- (BOOL) isHidden [implementation]
Returns YES if the receiver is hidden.
Definition at line 1179 of file CPView.j.
- (BOOL) isHiddenOrHasHiddenAncestor [implementation]
Returns YES if the receiver is hidden, or one of it's ancestor views is hidden. NO, otherwise.
Definition at line 1224 of file CPView.j.
Referenced by canBecomeKeyView.
- (BOOL) isInFullScreenMode [implementation]
Returns YES if the receiver is currently in full screen mode.
Definition at line 1134 of file CPView.j.
- (BOOL) isOpaque [implementation]
Returns whether the receiver is completely opaque. By default, returns NO.
Definition at line 1798 of file CPView.j.
Referenced by mouseDownCanMoveWindow.
+ (CPSet) keyPathsForValuesAffectingBounds [implementation]
Definition at line 241 of file CPView.j.
References CPSet::setWithObjects:.
+ (CPSet) keyPathsForValuesAffectingFrame [implementation]
Definition at line 236 of file CPView.j.
References CPSet::setWithObjects:.
- (CALayer) layer [implementation]
Returns the core animation layer used by the receiver.
Definition at line 2043 of file CPView.j.
- (CPView) layoutEphemeralSubviewNamed: (CPString) aViewName positioned: (CPWindowOrderingMode) anOrderingMode relativeToEphemeralSubviewNamed: (CPString) relativeToViewName [implementation]
Definition at line 2302 of file CPView.j.
References addSubview:positioned:relativeTo:, createEphemeralSubviewNamed:, frame, rectForEphemeralSubviewNamed:, and CPSet::set.
- (void) layoutIfNeeded [implementation]
Definition at line 1781 of file CPView.j.
References layoutSubviews.
- (void) layoutSubviews [implementation]
Definition at line 1791 of file CPView.j.
Referenced by layoutIfNeeded.
- (void) lockFocus [implementation]
Locks focus on the receiver, so drawing commands apply to it.
Definition at line 1729 of file CPView.j.
References CGBitmapGraphicsContextCreate(), CGContextSaveGState(), CPDOMDisplayServerAppendChild, CPGraphicsContext::graphicsContextWithGraphicsPort:flipped:, and CPGraphicsContext::setCurrentContext:.
Referenced by displayRectIgnoringOpacity:inContext:.
- (void) mouseDown: (CPEvent) anEvent [implementation]
Definition at line 1296 of file CPView.j.
- (BOOL) mouseDownCanMoveWindow [implementation]
Returns YES if mouse events aren't needed by the receiver and can be sent to the superview. The default implementation returns NO if the view is opaque.
Definition at line 1291 of file CPView.j.
References isOpaque.
- (BOOL) needsDisplay [implementation]
Definition at line 1671 of file CPView.j.
- (CPView) nextKeyView [implementation]
Definition at line 1963 of file CPView.j.
Referenced by encodeWithCoder:, and nextValidKeyView.
- (CPView) nextValidKeyView [implementation]
Definition at line 1968 of file CPView.j.
References canBecomeKeyView, and nextKeyView.
Referenced by CPWindow::selectKeyViewFollowingView:, and setHidden:.
- (BOOL) performKeyEquivalent: (CPEvent) anEvent [implementation]
Definition at line 1946 of file CPView.j.
Referenced by CPWindow::performKeyEquivalent:.
- (BOOL) postsBoundsChangedNotifications [implementation]
Returns YES if the receiver posts a CPViewBoundsDidChangeNotification when its bounds is changed.
Definition at line 1555 of file CPView.j.
- (BOOL) postsFrameChangedNotifications [implementation]
Returns YES if the receiver posts a CPViewFrameDidChangeNotification if its frame is changed.
Definition at line 1520 of file CPView.j.
- (CPView) previousKeyView [implementation]
Definition at line 1978 of file CPView.j.
Referenced by encodeWithCoder:, and previousValidKeyView.
- (CPView) previousValidKeyView [implementation]
Definition at line 1983 of file CPView.j.
References canBecomeKeyView, and previousKeyView.
Referenced by CPWindow::selectKeyViewPrecedingView:.
- (CGRect) rectForEphemeralSubviewNamed: (CPString) aViewName [implementation]
Definition at line 2297 of file CPView.j.
Referenced by layoutEphemeralSubviewNamed:positioned:relativeToEphemeralSubviewNamed:.
- (void) reflectScrolledClipView: (CPClipView) aClipView [implementation]
Notifies the receiver (superview of a CPClipView) that the clip view bounds or the document view bounds have changed.
Parameters:
aClipView the clip view of the superview being notified
Definition at line 1938 of file CPView.j.
- (CPArray) registeredDraggedTypes [implementation]
Returns an array of all types the receiver accepts for dragging operations.
Returns:
an array of CPPasteBoards
Definition at line 1612 of file CPView.j.
- (void) registerForDraggedTypes: (CPArray) pasteboardTypes [implementation]
Sets the receiver's list of acceptable data types for a dragging operation.
Parameters:
pasteboardTypes an array of CPPasteboards
Definition at line 1594 of file CPView.j.
References window.
- (void) removeFromSuperview [implementation]
Removes the receiver from it's container view and window. Does nothing if there's no container view.
Definition at line 439 of file CPView.j.
References CPDOMDisplayServerRemoveChild, and window.
Referenced by replaceSubview:with:.
- (void) replaceSubview: (CPView) aSubview with: (CPView) aView [implementation]
Replaces the specified child view with another view
Parameters:
aSubview the view to replace
aView the replacement view
Definition at line 464 of file CPView.j.
References removeFromSuperview.
- (void) resizeSubviewsWithOldSize: (CGSize) aSize [implementation]
Initiates -superviewSizeChanged: messages to subviews.
Parameters:
aSize the size for the subviews
Definition at line 1018 of file CPView.j.
Referenced by setFrameSize:.
- (void) resizeWithOldSuperviewSize: (CGSize) aSize [implementation]
Notifies subviews that the superview changed size.
Parameters:
aSize the size of the old superview
Definition at line 987 of file CPView.j.
References autoresizingMask, CPViewHeightSizable, CPViewMaxXMargin, CPViewMaxYMargin, CPViewMinXMargin, CPViewMinYMargin, CPViewNotSizable, CPViewWidthSizable, frame, and setFrame:.
- (void) scrollClipView: (CPClipView) aClipView toPoint: (CGPoint) aPoint [implementation]
Scrolls the clip view to a specified point
Parameters:
the clip view to scoll
the point to scroll to
Definition at line 1928 of file CPView.j.
References CPClipView::scrollToPoint:.
- (void) scrollPoint: (CGPoint) aPoint [implementation]
Changes the receiver's frame origin to a 'constrained' aPoint.
Parameters:
aPoint the proposed frame origin
Definition at line 1831 of file CPView.j.
References convertPoint:toView:.
- (void) scrollRect: (CGRect) aRect by: (float) anAmount [implementation]
Should be overridden by subclasses.
Definition at line 1903 of file CPView.j.
- (BOOL) scrollRectToVisible: (CGRect) aRect [implementation]
Scrolls the nearest ancestor CPClipView a minimum amount so aRect can become visible.
Parameters:
aRect the area to become visible
Returns:
<codeYES if any scrolling occurred, NO otherwise.
Definition at line 1846 of file CPView.j.
References CGRectContainsRect(), CGRectGetMinY(), CGRectIntersection(), and visibleRect.
- (void) setAlphaValue: (float) anAlphaValue [implementation]
Sets the opacity of the receiver. The value must be in the range of 0.0 to 1.0, where 0.0 is completely transparent and 1.0 is completely opaque.
Parameters:
anAlphaValue an alpha value ranging from 0.0 to 1.0.
Definition at line 1189 of file CPView.j.
References CPFeatureIsCompatible().
Referenced by initWithCoder:.
- (void) setAutoresizesSubviews: (BOOL) aFlag [implementation]
Specifies whether the receiver view should automatically resize its subviews when its -setFrameSize: method receives a change.
Parameters:
aFlag If YES, then subviews will automatically be resized when this view is resized. NO means the views will not be resized automatically.
Definition at line 1033 of file CPView.j.
- (void) setAutoresizingMask: (unsigned) aMask [implementation]
Determines automatic resizing behavior.
Parameters:
aMask a bit mask with options
Definition at line 1051 of file CPView.j.
Referenced by CPButtonBar::addSubview:, enterFullScreenMode:withOptions:, and exitFullScreenModeWithOptions:.
- (void) setBackgroundColor: (CPColor) aColor [implementation]
Sets the background color of the receiver.
Parameters:
aColor the new color for the receiver's background
Definition at line 1306 of file CPView.j.
References CPDOMDisplayServerSetStyleLeftBottom, CPDOMDisplayServerSetStyleLeftTop, CPDOMDisplayServerSetStyleRightBottom, CPDOMDisplayServerSetStyleRightTop, CPDOMDisplayServerSetStyleSize, height, MIN, size, and width.
Referenced by initWithCoder:.
- (void) setBounds: (CGRect) bounds [implementation]
Sets the receiver's bounds. The bounds define the size and location of the receiver inside it's frame. Posts a CPViewBoundsDidChangeNotification to the default notification center if the receiver is configured to do so.
Parameters:
bounds the new bounds
Definition at line 866 of file CPView.j.
References setBoundsOrigin:, and setBoundsSize:.
- (void) setBoundsOrigin: (CGPoint) aPoint [implementation]
Sets the location of the receiver inside its frame. The method posts a CPViewBoundsDidChangeNotification to the default notification center if the receiver is configured to do so.
Parameters:
aPoint the new location for the receiver
Definition at line 907 of file CPView.j.
References CGAffineTransformInvert(), and CPDOMDisplayServerSetStyleLeftTop.
Referenced by setBounds:.
- (void) setBoundsSize: (CGSize) aSize [implementation]
Sets the receiver's size inside its frame. The method posts a CPViewBoundsDidChangeNotification to the default notification center if the receiver is configured to do so.
Parameters:
aSize the new size for the receiver
Definition at line 950 of file CPView.j.
References size.
Referenced by setBounds:.
- (void) setCenter: (CGPoint) aPoint [implementation]
Moves the center of the receiver's frame to the provided point. The point is defined in the superview's coordinate system. The method posts a CPViewFrameDidChangeNotification to the default notification center if the receiver is configured to do so. If the specified origin is the same as the frame's current origin, the method will simply return (and no notification will be posted).
Parameters:
aPoint the new origin point
Definition at line 746 of file CPView.j.
References setFrameOrigin:.
- (void) setFrame: (CGRect) aFrame [implementation]
Sets the frame size of the receiver to the dimensions and origin of the provided rectangle in the coordinate system of the superview. The method also posts an CPViewFrameDidChangeNotification to the notification center if the receiver is configured to do so. If the frame is the same as the current frame, the method simply returns (and no notificaion is posted).
Parameters:
aFrame the rectangle specifying the new origin and size of the receiver
Definition at line 704 of file CPView.j.
References setFrameOrigin:, and setFrameSize:.
Referenced by enterFullScreenMode:withOptions:, exitFullScreenModeWithOptions:, resizeWithOldSuperviewSize:, and CPBox::setContentView:.
- (void) setFrameOrigin: (CGPoint) aPoint [implementation]
Sets the receiver's frame origin to the provided point. The point is defined in the superview's coordinate system. The method posts a CPViewFrameDidChangeNotification to the default notification center if the receiver is configured to do so. If the specified origin is the same as the frame's current origin, the method will simply return (and no notification will be posted).
Parameters:
aPoint the new origin point
Definition at line 767 of file CPView.j.
References CPDOMDisplayServerSetStyleLeftTop.
Referenced by CPDragServer::dragView:fromWindow:at:offset:event:pasteboard:source:slideBack:, setCenter:, and setFrame:.
- (void) setFrameSize: (CGSize) aSize [implementation]
Sets the receiver's frame size. If aSize is the same as the frame's current dimensions, this method simply returns. The method posts a CPViewFrameDidChangeNotification to the default notification center if the receiver is configured to do so.
Parameters:
aSize the new size for the frame
Definition at line 793 of file CPView.j.
References CPDOMDisplayServerSetSize, CPDOMDisplayServerSetStyleSize, height, resizeSubviewsWithOldSize:, setNeedsDisplay:, setNeedsLayout, size, and width.
Referenced by setFrame:.
- (void) setHidden: (BOOL) aFlag [implementation]
Sets whether the receiver should be hidden.
Parameters:
aFlag YES makes the receiver hidden.
Definition at line 1143 of file CPView.j.
References nextValidKeyView.
Referenced by initWithCoder:.
- (void) setHitTests: (BOOL) shouldHitTest [implementation]
Set whether or not the view should respond to hit tests.
Parameters:
shouldHitTest should be YES if this view should respond to hit tests, NO otherwise.
Definition at line 1258 of file CPView.j.
- (void) setLayer: (CALayer) aLayer [implementation]
Sets the core animation layer to be used by this receiver.
Definition at line 2011 of file CPView.j.
References bounds, and CGRectMakeCopy().
- (void) setNeedsDisplay: (BOOL) aFlag [implementation]
Marks the entire view as dirty, and needing a redraw.
Definition at line 1645 of file CPView.j.
References bounds, and setNeedsDisplayInRect:.
Referenced by initWithCoder:, setFrameSize:, setThemeState:, setValue:forThemeAttribute:, setValue:forThemeAttribute:inState:, unsetThemeState:, viewDidChangeTheme, and viewDidMoveToSuperview.
- (void) setNeedsDisplayInRect: (CPRect) aRect [implementation]
Marks the area denoted by aRect as dirty, and initiates a redraw on it.
Parameters:
aRect the area that needs to be redrawn
Definition at line 1655 of file CPView.j.
References CGRectUnion(), and CPViewHasCustomDrawRect.
Referenced by setNeedsDisplay:.
- (void) setNeedsLayout [implementation]
Definition at line 1771 of file CPView.j.
References CPViewHasCustomLayoutSubviews.
Referenced by initWithCoder:, setFrameSize:, setThemeState:, setValue:forThemeAttribute:, setValue:forThemeAttribute:inState:, unsetThemeState:, and viewDidChangeTheme.
- (void) setNextKeyView: (CPView) next [implementation]
Definition at line 1998 of file CPView.j.
- (void) setPostsBoundsChangedNotifications: (BOOL) shouldPostBoundsChangedNotifications [implementation]
Sets whether the receiver posts a CPViewBoundsDidChangeNotification notification to the default notification center when its bounds is changed. The default is NO. Methods that could cause a bounds change notification are:
setBounds:
setBoundsSize:
setBoundsOrigin:
Parameters:
shouldPostBoundsChangedNotifications YES makes the receiver post notifications on bounds changes
Definition at line 1537 of file CPView.j.
- (void) setPostsFrameChangedNotifications: (BOOL) shouldPostFrameChangedNotifications [implementation]
Sets whether the receiver posts a CPViewFrameDidChangeNotification notification to the default notification center when its frame is changed. The default is NO. Methods that could cause a frame change notification are:
setFrame:
setFrameSize:
setFrameOrigin:
Parameters:
shouldPostFrameChangedNotifications YES makes the receiver post notifications on frame changes (size or origin)
Definition at line 1504 of file CPView.j.
- (void) setSubviews: (CPArray) newSubviews [implementation]
Definition at line 476 of file CPView.j.
References addSubview:, CPDOMDisplayServerAppendChild, CPDOMDisplayServerRemoveChild, and CPException::raise:reason:.
- (void) setTag: (CPInteger) aTag [implementation]
Definition at line 659 of file CPView.j.
- (void) setTheme: (CPTheme) aTheme [implementation]
Definition at line 2189 of file CPView.j.
References viewDidChangeTheme.
- (BOOL) setThemeState: (CPThemeState) aState [implementation]
Definition at line 2081 of file CPView.j.
References CPThemeState(), setNeedsDisplay:, and setNeedsLayout.
- (void) setupViewFlags [implementation]
Definition at line 215 of file CPView.j.
References CPViewFlags, CPViewHasCustomDrawRect, and CPViewHasCustomLayoutSubviews.
Referenced by initWithCoder:, and initWithFrame:.
- (void) setValue: (id) aValue forThemeAttribute: (CPString) aName [implementation]
Definition at line 2252 of file CPView.j.
References currentValueForThemeAttribute:, CPException::raise:reason:, setNeedsDisplay:, and setNeedsLayout.
- (void) setValue: (id) aValue forThemeAttribute: (CPString) aName inState: (CPThemeState) aState [implementation]
Definition at line 2236 of file CPView.j.
References currentValueForThemeAttribute:, CPException::raise:reason:, setNeedsDisplay:, and setNeedsLayout.
- (void) setWantsLayer: (BOOL) aFlag [implementation]
Sets whether the receiver wants a core animation layer.
Parameters:
\c YES means the receiver wants a layer.
Definition at line 2052 of file CPView.j.
- (CPArray) subviews [implementation]
Returns an array of all the views contained as direct children of the receiver
Returns:
an array of CPViews
Definition at line 314 of file CPView.j.
- (CPView) superview [implementation]
Returns the container view of the receiver
Returns:
the receiver's containing view
Definition at line 305 of file CPView.j.
Referenced by autoscroll:, and CPBox::boxEnclosingView:.
- (CPInteger) tag [implementation]
Definition at line 664 of file CPView.j.
- (CPTheme) theme [implementation]
Definition at line 2199 of file CPView.j.
Referenced by viewDidChangeTheme.
+ (CPDictionary) themeAttributes [implementation]
Definition at line 2118 of file CPView.j.
+ (CPString) themeClass [implementation]
Definition at line 2113 of file CPView.j.
Referenced by initWithCoder:, and viewDidChangeTheme.
- (unsigned) themeState [implementation]
Definition at line 2071 of file CPView.j.
- (void) unlockFocus [implementation]
Takes focus away from the receiver, and restores it to the previous view.
Definition at line 1764 of file CPView.j.
References CGContextRestoreGState(), and CPGraphicsContext::setCurrentContext:.
Referenced by displayRectIgnoringOpacity:inContext:.
- (void) unregisterDraggedTypes [implementation]
Resets the array of acceptable data types for a dragging operation.
Definition at line 1623 of file CPView.j.
References CPSet::set, and window.
- (BOOL) unsetThemeState: (CPThemeState) aState [implementation]
Definition at line 2096 of file CPView.j.
References CPThemeState(), setNeedsDisplay:, and setNeedsLayout.
- (id) valueForThemeAttribute: (CPString) aName [implementation]
Definition at line 2276 of file CPView.j.
References CPException::raise:reason:.
- (id) valueForThemeAttribute: (CPString) aName inState: (CPThemeState) aState [implementation]
Definition at line 2268 of file CPView.j.
References CPException::raise:reason:.
- (void) viewDidChangeTheme [implementation]
Definition at line 2204 of file CPView.j.
References setNeedsDisplay:, setNeedsLayout, theme, and themeClass.
Referenced by setTheme:.
- (void) viewDidMoveToSuperview [implementation]
Called when the receiver's superview has changed.
Definition at line 598 of file CPView.j.
References setNeedsDisplay:.
- (void) viewDidMoveToWindow [implementation]
Called when the receiver has been moved to a new CPWindow.
Definition at line 607 of file CPView.j.
- (void) viewWillDraw [implementation]
Definition at line 1722 of file CPView.j.
Referenced by displayRect:.
- (void) viewWillMoveToSuperview: (CPView) aView [implementation]
Called when the receiver is about to be moved to a new view.
Parameters:
aView the view to which the receiver will be moved
Definition at line 615 of file CPView.j.
- (void) viewWillMoveToWindow: (CPWindow) aWindow [implementation]
Called when the receiver is about to be moved to a new window.
Parameters:
aWindow the window to which the receiver will be moved.
Definition at line 623 of file CPView.j.
- (void) viewWithTag: (CPInteger) aTag [implementation]
Definition at line 669 of file CPView.j.
References tag.
- (CGRect) visibleRect [implementation]
Returns the rectangle of the receiver not clipped by its superview.
Definition at line 1806 of file CPView.j.
References CGRectIntersection().
Referenced by display, and scrollRectToVisible:.
- (BOOL) wantsLayer [implementation]
Returns YES if the receiver uses a CALayer
Returns:
YES if the receiver uses a CALayer
Definition at line 2061 of file CPView.j.
- (void) willRemoveSubview: (CPView) aView [implementation]
Called when the receiver is about to be remove one of its subviews.
Parameters:
aView the view that will be removed
Definition at line 631 of file CPView.j.
- (CPWindow) window [implementation]
Returns the window containing this receiver
Definition at line 322 of file CPView.j.
Referenced by exitFullScreenModeWithOptions:, CPMenu::popUpContextMenu:withEvent:forView:withFont:, registerForDraggedTypes:, removeFromSuperview, and unregisterDraggedTypes.
The documentation for this class was generated from the following file:
AppKit/CPView.j