Cappuccino: CPPlatformWindow Class Reference
CPPlatformWindow Class Reference
Public Member Functions
(id) - initWithContentRect: [implementation]
(id) - init [implementation]
(CGRect) - contentRect [implementation]
(CGRect) - contentBounds [implementation]
(CGRect) - visibleFrame [implementation]
(void) - usableContentFrame [implementation]
(void) - setContentRect: [implementation]
(void) - updateFromNativeContentRect [implementation]
(CGPoint) - convertBaseToScreen: [implementation]
(CGPoint) - convertScreenToBase: [implementation]
(BOOL) - isVisible [implementation]
(void) - deminiaturize: [implementation]
(void) - miniaturize: [implementation]
(void) - setLevel: [implementation]
(void) - setHasShadow: [implementation]
(void) - setShadowStyle: [implementation]
(BOOL) - supportsFullPlatformWindows [implementation]
(CGRect) - nativeContentRect [implementation]
(void) - updateNativeContentRect [implementation]
(void) - orderBack: [implementation]
(void) - createDOMElements [implementation]
(void) - platformDidClearBodyElement: [implementation]
(void) - registerDOMWindow [implementation]
(void) - orderFront: [implementation]
(void) - orderOut: [implementation]
(void) - dragEvent: [implementation]
(void) - keyEvent: [implementation]
(void) - copyEvent: [implementation]
(void) - pasteEvent: [implementation]
(void) - scrollEvent: [implementation]
(void) - resizeEvent: [implementation]
(void) - touchEvent: [implementation]
(void) - mouseEvent: [implementation]
() - if [implementation]
(CPDOMWindowLayer) - layerAtLevel:create: [implementation]
(void) - order:window:relativeTo: [implementation]
(CPWindow) - hitTest: [implementation]
Static Public Member Functions
(CPSet) + visiblePlatformWindows [implementation]
(CPPlatformWindow) + primaryPlatformWindow [implementation]
(void) + setPrimaryPlatformWindow: [implementation]
(void) + preventCharacterKeysFromPropagating: [implementation]
(void) + preventCharacterKeyFromPropagating: [implementation]
(void) + clearCharacterKeysToPreventFromPropagating [implementation]
(void) + preventKeyCodesFromPropagating: [implementation]
(void) + preventKeyCodeFromPropagating: [implementation]
(void) + clearKeyCodesToPreventFromPropagating [implementation]
Detailed Description
Definition at line 31 of file CPPlatformWindow.j.
Member Function Documentation
+ (void) clearCharacterKeysToPreventFromPropagating [implementation]
Clear the list of characters for which we are not sending keypresses to the browser.
Definition at line 1296 of file CPPlatformWindow+DOM.j.
References CharacterKeysToPrevent.
+ (void) clearKeyCodesToPreventFromPropagating [implementation]
Clear the list of keyCodes for which we are not sending keypresses to the browser.
Definition at line 1323 of file CPPlatformWindow+DOM.j.
References KeyCodesToPrevent.
- (CGRect) contentBounds [implementation]
Definition at line 114 of file CPPlatformWindow.j.
References contentRect.
Referenced by CPView::enterFullScreenMode:withOptions:, and visibleFrame.
- (CGRect) contentRect [implementation]
Definition at line 109 of file CPPlatformWindow.j.
Referenced by contentBounds, convertBaseToScreen:, convertScreenToBase:, nativeContentRect, resizeEvent:, and updateNativeContentRect.
- (CGPoint) convertBaseToScreen: (CGPoint) aPoint [implementation]
Definition at line 160 of file CPPlatformWindow.j.
References contentRect.
- (CGPoint) convertScreenToBase: (CGPoint) aPoint [implementation]
Definition at line 167 of file CPPlatformWindow.j.
References contentRect.
- (void) copyEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 725 of file CPPlatformWindow+DOM.j.
References CPKeyCodes, CPRunLoop::currentRunLoop, CPEvent::keyEventWithType:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:, and CPRunLoop::limitDateForMode:.
- (void) createDOMElements [implementation]
Definition at line 231 of file CPPlatformWindow+DOM.j.
Referenced by platformDidClearBodyElement:, and registerDOMWindow.
- (void) deminiaturize: (id) sender [implementation]
Definition at line 183 of file CPPlatformWindow.j.
Referenced by CPWindow::deminiaturize:.
- (void) dragEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 478 of file CPPlatformWindow+DOM.j.
References CPDragOperationCopy, CPDragOperationGeneric, CPDragOperationLink, CPDragOperationMove, CPDragOperationNone, CPDragOperationPrivate, CPFeatureIsCompatible(), CPHTML5DragAndDropSourceYOffBy1, CPRunLoop::currentRunLoop, CPPlatform::isBrowser, CPRunLoop::limitDateForMode:, CPDragServer::sharedDragServer, and CPEvent::type.
- (CPWindow) hitTest: (CPPoint) location [implementation]
Definition at line 1245 of file CPPlatformWindow+DOM.j.
Referenced by mouseEvent:, and scrollEvent:.
- CPPlatformWindow: (!) layer [implementation]
- (id) init [implementation]
Definition at line 104 of file CPPlatformWindow.j.
References initWithContentRect:.
- (id) initWithContentRect: (CGRect) aRect [implementation]
Definition at line 85 of file CPPlatformWindow.j.
References CPDictionary::dictionary.
Referenced by init.
- (BOOL) isVisible [implementation]
Definition at line 174 of file CPPlatformWindow.j.
- (void) keyEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 570 of file CPPlatformWindow+DOM.j.
References CharacterKeysToPrevent, CPAlternateKeyMask, CPApp, CPCommandKeyMask, CPControlKeyMask, CPDOMEventStop, CPKeyCodes, CPShiftKeyMask, CPRunLoop::currentRunLoop, KeyCodesToPrevent, CPEvent::keyEventWithType:location:modifierFlags:timestamp:windowNumber:context:characters:charactersIgnoringModifiers:isARepeat:keyCode:, CPRunLoop::limitDateForMode:, MozKeyCodeToKeyCodeMap, and StopDOMEventPropagation.
- (CPDOMWindowLayer) layerAtLevel: (int) aLevel create: (BOOL) aFlag [implementation]
Definition at line 1122 of file CPPlatformWindow+DOM.j.
Referenced by order:window:relativeTo:.
- (void) miniaturize: (id) sender [implementation]
Definition at line 191 of file CPPlatformWindow.j.
Referenced by CPWindow::miniaturize:.
- (void) mouseEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 989 of file CPPlatformWindow+DOM.j.
References CPAlternateKeyMask, CPCommandKeyMask, CPControlKeyMask, CPDOMEventGetClickCount, CPDOMEventMouseDown, CPDOMEventMouseUp, CPDOMEventStop, CPLeftMouseDown, CPLeftMouseDragged, CPLeftMouseUp, CPMouseMoved, CPShiftKeyMask, CPRunLoop::currentRunLoop, hitTest:, CPRunLoop::limitDateForMode:, mouseEvent:, CPEvent::mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:, CPDragServer::sharedDragServer, StopDOMEventPropagation, and supportsNativeDragAndDrop.
Referenced by mouseEvent:, and touchEvent:.
- (CGRect) nativeContentRect [implementation]
Definition at line 169 of file CPPlatformWindow+DOM.j.
References contentRect.
Referenced by updateFromNativeContentRect, and updateNativeContentRect.
- (void) order: (CPWindowOrderingMode) aPlace window: (CPWindow) aWindow relativeTo: (CPWindow) otherWindow [implementation]
Definition at line 1158 of file CPPlatformWindow+DOM.j.
References CPWindowOut, CPPlatform::initializeScreenIfNecessary, layerAtLevel:create:, and CPWindow::level.
- (void) orderBack: (id) aSender [implementation]
Definition at line 225 of file CPPlatformWindow+DOM.j.
- (void) orderFront: (id) aSender [implementation]
Definition at line 443 of file CPPlatformWindow+DOM.j.
References CPCursor::currentCursor, and registerDOMWindow.
- (void) orderOut: (id) aSender [implementation]
Definition at line 470 of file CPPlatformWindow+DOM.j.
- (void) pasteEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 754 of file CPPlatformWindow+DOM.j.
References CPRunLoop::currentRunLoop, and CPRunLoop::limitDateForMode:.
- (void) platformDidClearBodyElement: (CPNotification) aNotification [implementation]
Definition at line 258 of file CPPlatformWindow+DOM.j.
References createDOMElements.
+ (void) preventCharacterKeyFromPropagating: (CPString) character [implementation]
Parameters:
character a character to stop propagating keypresses to the browser.
Definition at line 1288 of file CPPlatformWindow+DOM.j.
References CharacterKeysToPrevent.
+ (void) preventCharacterKeysFromPropagating: (CPArray) characters [implementation]
When using command (mac) or control (windows), keys are propagated to the browser by default. To prevent a character key from propagating (to prevent its default action, and instead use it in your own application), use these methods. These methods are additive -- the list builds until you clear it.
Parameters:
characters a list of characters to stop propagating keypresses to the browser.
Definition at line 1279 of file CPPlatformWindow+DOM.j.
References CharacterKeysToPrevent.
+ (void) preventKeyCodeFromPropagating: (CPString) keyCode [implementation]
Prevent this keyCode from sending its key events to the browser.
Parameters:
keyCode a keycode to prevent propagation.
Definition at line 1315 of file CPPlatformWindow+DOM.j.
References KeyCodesToPrevent.
+ (void) preventKeyCodesFromPropagating: (CPArray) keyCodes [implementation]
Prevent these keyCodes from sending their keypresses to the browser.
Parameters:
keyCodes an array of keycodes to prevent propagation.
Definition at line 1305 of file CPPlatformWindow+DOM.j.
References KeyCodesToPrevent.
+ (CPPlatformWindow) primaryPlatformWindow [implementation]
Definition at line 75 of file CPPlatformWindow.j.
References PrimaryPlatformWindow.
Referenced by CPView::enterFullScreenMode:withOptions:, CPWindow::initWithContentRect:styleMask:, and CPMenu::setMenuBarVisible:.
- (void) registerDOMWindow [implementation]
Definition at line 263 of file CPPlatformWindow+DOM.j.
References CPNotificationCenter::addObserver:selector:name:object:, createDOMElements, CPNotificationCenter::defaultCenter, and updateFromNativeContentRect.
Referenced by orderFront:.
- (void) resizeEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 912 of file CPPlatformWindow+DOM.j.
References contentRect, CPRunLoop::currentRunLoop, CPRunLoop::limitDateForMode:, and updateFromNativeContentRect.
Referenced by CPMenu::setMenuBarVisible:.
- (void) scrollEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 827 of file CPPlatformWindow+DOM.j.
References CPAlternateKeyMask, CPCommandKeyMask, CPControlKeyMask, CPDOMEventStop, CPFeatureIsCompatible(), CPJavaScriptMouseWheelValues_8_15, CPJavaScriptNegativeMouseWheelValues, CPShiftKeyMask, CPRunLoop::currentRunLoop, hitTest:, CPRunLoop::limitDateForMode:, CPEvent::mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:, and StopDOMEventPropagation.
- (void) setContentRect: (CGRect) aRect [implementation]
Definition at line 145 of file CPPlatformWindow.j.
References updateNativeContentRect.
Referenced by updateFromNativeContentRect.
- (void) setHasShadow: (BOOL) shouldHaveShadow [implementation]
Definition at line 209 of file CPPlatformWindow.j.
- (void) setLevel: (CPInteger) aLevel [implementation]
Definition at line 199 of file CPPlatformWindow.j.
+ (void) setPrimaryPlatformWindow: (CPPlatformWindow) aPlatformWindow [implementation]
Definition at line 80 of file CPPlatformWindow.j.
References PrimaryPlatformWindow.
- (void) setShadowStyle: (int) aStyle [implementation]
Definition at line 219 of file CPPlatformWindow.j.
Referenced by CPWindow::setShadowStyle:.
- (BOOL) supportsFullPlatformWindows [implementation]
Definition at line 229 of file CPPlatformWindow.j.
References CPPlatform::isBrowser.
- (void) touchEvent: (DOMEvent) aDOMEvent [implementation]
Definition at line 943 of file CPPlatformWindow+DOM.j.
References CPDOMEventMouseDown, CPDOMEventMouseMoved, CPDOMEventMouseUp, CPDOMEventTouchCancel, CPDOMEventTouchEnd, CPDOMEventTouchMove, CPDOMEventTouchStart, and mouseEvent:.
- (void) updateFromNativeContentRect [implementation]
Definition at line 155 of file CPPlatformWindow.j.
References nativeContentRect, and setContentRect:.
Referenced by registerDOMWindow, and resizeEvent:.
- (void) updateNativeContentRect [implementation]
Definition at line 200 of file CPPlatformWindow+DOM.j.
References contentRect, nativeContentRect, and size.
Referenced by setContentRect:.
- (void) usableContentFrame [implementation]
Definition at line 140 of file CPPlatformWindow.j.
References visibleFrame.
- (CGRect) visibleFrame [implementation]
Definition at line 123 of file CPPlatformWindow.j.
References CGPointMakeZero(), contentBounds, and frame.
Referenced by usableContentFrame.
+ (CPSet) visiblePlatformWindows [implementation]
Definition at line 70 of file CPPlatformWindow.j.
References CPSet::set.
Referenced by CPCursor::set.
The documentation for this class was generated from the following files:
AppKit/Platform/CPPlatformWindow.j
AppKit/Platform/DOM/CPPlatformWindow+DOM.j