Cappuccino: CPSplitView Class Reference
CPSplitView Class Reference
[AppKit]
Public Member Functions
(id) - initWithFrame: [implementation]
(float) - dividerThickness [implementation]
(BOOL) - isVertical [implementation]
(void) - setVertical: [implementation]
(BOOL) - isPaneSplitter [implementation]
(void) - setIsPaneSplitter: [implementation]
(void) - didAddSubview: [implementation]
(BOOL) - isSubviewCollapsed: [implementation]
(CGRect) - rectOfDividerAtIndex: [implementation]
(CGRect) - effectiveRectOfDividerAtIndex: [implementation]
(void) - drawRect: [implementation]
(void) - drawDividerInRect: [implementation]
(void) - viewWillDraw [implementation]
(BOOL) - cursorAtPoint:hitDividerAtIndex: [implementation]
(CPView) - hitTest: [implementation]
(void) - trackDivider: [implementation]
(void) - mouseDown: [implementation]
(float) - maxPossiblePositionOfDividerAtIndex: [implementation]
(float) - minPossiblePositionOfDividerAtIndex: [implementation]
(void) - setPosition:ofDividerAtIndex: [implementation]
(void) - setFrameSize: [implementation]
(void) - resizeSubviewsWithOldSize: [implementation]
(void) - setDelegate: [implementation]
(id) - initWithCoder: [implementation]
(void) - encodeWithCoder: [implementation]
Static Public Member Functions
(void) + initialize [implementation]
Detailed Description
Definition at line 41 of file CPSplitView.j.
Member Function Documentation
- (BOOL) cursorAtPoint: (CPPoint) aPoint hitDividerAtIndex: (int) anIndex [implementation]
Definition at line 269 of file CPSplitView.j.
References CGRectContainsPoint(), effectiveRectOfDividerAtIndex:, and frame.
- (void) didAddSubview: (CPView) aSubview [implementation]
Definition at line 160 of file CPSplitView.j.
- (float) dividerThickness [implementation]
Definition at line 87 of file CPSplitView.j.
Referenced by maxPossiblePositionOfDividerAtIndex:, minPossiblePositionOfDividerAtIndex:, rectOfDividerAtIndex:, resizeSubviewsWithOldSize:, setPosition:ofDividerAtIndex:, and setVertical:.
- (void) drawDividerInRect: (CGRect) aRect [implementation]
Definition at line 207 of file CPSplitView.j.
References CPDOMDisplayServerAppendChild, CPDOMDisplayServerSetStyleLeftTop, and CPDOMDisplayServerSetStyleSize.
Referenced by drawRect:.
- (void) drawRect: (CGRect) rect [implementation]
Definition at line 196 of file CPSplitView.j.
References drawDividerInRect:, and rectOfDividerAtIndex:.
- (CGRect) effectiveRectOfDividerAtIndex: (int) aDivider [implementation]
Definition at line 184 of file CPSplitView.j.
References rectOfDividerAtIndex:.
Referenced by cursorAtPoint:hitDividerAtIndex:.
- (void) encodeWithCoder: (CPCoder) aCoder [implementation]
Definition at line 595 of file CPSplitView.j.
- (CPView) hitTest: (CGPoint) aPoint [implementation]
Definition at line 285 of file CPSplitView.j.
References CGRectContainsPoint(), and frame.
+ (void) initialize [implementation]
Definition at line 63 of file CPSplitView.j.
References CPBundle::bundleForClass:, CPSplitViewHorizontalImage, and CPSplitViewVerticalImage.
- (id) initWithCoder: (CPCoder) aCoder [implementation]
Definition at line 572 of file CPSplitView.j.
References CPNotFound.
- (id) initWithFrame: (CGRect) aFrame [implementation]
Definition at line 73 of file CPSplitView.j.
References CPNotFound.
- (BOOL) isPaneSplitter [implementation]
Definition at line 138 of file CPSplitView.j.
- (BOOL) isSubviewCollapsed: (CPView) subview [implementation]
Definition at line 166 of file CPSplitView.j.
References CPView::frame.
- (BOOL) isVertical [implementation]
Definition at line 92 of file CPSplitView.j.
Referenced by resizeSubviewsWithOldSize:.
- (float) maxPossiblePositionOfDividerAtIndex: (int) dividerIndex [implementation]
Definition at line 386 of file CPSplitView.j.
References dividerThickness, and frame.
Referenced by setPosition:ofDividerAtIndex:, and trackDivider:.
- (float) minPossiblePositionOfDividerAtIndex: (int) dividerIndex [implementation]
Definition at line 396 of file CPSplitView.j.
References dividerThickness, and frame.
Referenced by setPosition:ofDividerAtIndex:, and trackDivider:.
- (void) mouseDown: (CPEvent) anEvent [implementation]
Definition at line 380 of file CPSplitView.j.
References trackDivider:.
- (CGRect) rectOfDividerAtIndex: (int) aDivider [implementation]
Definition at line 171 of file CPSplitView.j.
References CGRectMakeZero(), dividerThickness, and frame.
Referenced by drawRect:, and effectiveRectOfDividerAtIndex:.
- (void) resizeSubviewsWithOldSize: (CPSize) oldSize [implementation]
Definition at line 459 of file CPSplitView.j.
References CGRectMakeCopy(), CPViewHeightSizable, CPViewWidthSizable, dividerThickness, frame, isVertical, MAX, and size.
- (void) setDelegate: (id) delegate [implementation]
Definition at line 529 of file CPSplitView.j.
References CPNotificationCenter::addObserver:selector:name:object:, CPNotificationCenter::defaultCenter, and CPNotificationCenter::removeObserver:name:object:.
- (void) setFrameSize: (CGSize) aSize [implementation]
Definition at line 450 of file CPSplitView.j.
- (void) setIsPaneSplitter: (BOOL) shouldBePaneSplitter [implementation]
Definition at line 143 of file CPSplitView.j.
- (void) setPosition: (float) position ofDividerAtIndex: (int) dividerIndex [implementation]
Definition at line 408 of file CPSplitView.j.
References dividerThickness, frame, MAX, maxPossiblePositionOfDividerAtIndex:, MIN, and minPossiblePositionOfDividerAtIndex:.
Referenced by trackDivider:.
- (void) setVertical: (BOOL) shouldBeVertical [implementation]
Definition at line 97 of file CPSplitView.j.
References CGRectMake(), dividerThickness, and frame.
- (void) trackDivider: (CPEvent) anEvent [implementation]
Definition at line 306 of file CPSplitView.j.
References CPLeftMouseDown, CPLeftMouseDragged, CPLeftMouseUp, CPNotFound, frame, CPEvent::locationInWindow, maxPossiblePositionOfDividerAtIndex:, minPossiblePositionOfDividerAtIndex:, setPosition:ofDividerAtIndex:, and CPEvent::type.
Referenced by mouseDown:.
- (void) viewWillDraw [implementation]
Definition at line 236 of file CPSplitView.j.
The documentation for this class was generated from the following file:
AppKit/CPSplitView.j