Cappuccino: CoreGraphics
CoreGraphics
Functions
function CGContextRelease ()
function CGContextRetain (aContext)
function CGGStateCreate ()
function CGGStateCreateCopy (aGState)
function CGBitmapGraphicsContextCreate ()
function CGContextSaveGState (aContext)
function CGContextRestoreGState (aContext)
function CGContextSetLineCap (aContext, aLineCap)
function CGContextSetLineJoin (aContext, aLineJoin)
function CGContextSetLineWidth (aContext, aLineWidth)
function CGContextSetMiterLimit (aContext, aMiterLimit)
function CGContextSetBlendMode (aContext, aBlendMode)
function CGContextAddArc (aContext, x, y, radius, startAngle, endAngle, clockwise)
function CGContextAddArcToPoint (aContext, x1, y1, x2, y2, radius)
function CGContextAddCurveToPoint (aContext, cp1x, cp1y, cp2x, cp2y, x, y)
function CGContextAddLines (aContext, points, count)
function CGContextAddLineToPoint (aContext, x, y)
function CGContextAddPath (aContext, aPath)
function CGContextAddQuadCurveToPoint (aContext, cpx, cpy, x, y)
function CGContextAddRect (aContext, aRect)
function CGContextAddRects (aContext, rects, count)
function CGContextBeginPath (aContext)
function CGContextClosePath (aContext)
function CGContextMoveToPoint (aContext, x, y)
function CGContextFillRect (aContext, aRect)
function CGContextFillRects (aContext, rects, count)
function CGContextStrokeRect (aContext, aRect)
function CGContextStrokeRectWithWidth (aContext, aRect, aWidth)
function CGContextConcatCTM (aContext, aTransform)
function CGContextGetCTM (aContext)
function CGContextRotateCTM (aContext, anAngle)
function CGContextScaleCTM (aContext, sx, sy)
function CGContextTranslateCTM (aContext, tx, ty)
function CGContextSetShadow (aContext, aSize, aBlur)
function CGContextSetShadowWithColor (aContext, aSize, aBlur, aColor)
function CGContextSetAlpha (aContext, anAlpha)
function CGContextEOFillPath (aContext)
function CGContextFillPath (aContext)
function CGContextAddEllipseInRect (aContext, aRect)
function CGContextFillEllipseInRect (aContext, aRect)
function CGContextStrokeEllipseInRect (aContext, aRect)
function CGContextStrokePath (aContext)
function CGContextStrokeLineSegments (aContext, points, count)
function CGContextSetFillColor (aContext, aColor)
function CGContextSetStrokeColor (aContext, aColor)
function CGContextFillRoundedRectangleInRect (aContext, aRect, aRadius, ne, se, sw, nw)
function CGContextStrokeRoundedRectangleInRect (aContext, aRect, aRadius, ne, se, sw, nw)
function CGPathCreateMutable ()
function CGPathCreateMutableCopy (aPath)
function CGPathCreateCopy (aPath)
function CGPathRelease (aPath)
function CGPathRetain (aPath)
function CGPathAddArc (aPath, aTransform, x, y, aRadius, aStartAngle, anEndAngle, isClockwise)
function CGPathAddArcToPoint (aPath, aTransform, x1, y1, x2, y2, aRadius)
function CGPathAddCurveToPoint (aPath, aTransform, cp1x, cp1y, cp2x, cp2y, x, y)
function CGPathAddLines (aPath, aTransform, points, count)
function CGPathAddLineToPoint (aPath, aTransform, x, y)
function CGPathAddPath (aPath, aTransform, anotherPath)
function CGPathAddQuadCurveToPoint (aPath, aTransform, cpx, cpy, x, y)
function CGPathAddRect (aPath, aTransform, aRect)
function CGPathAddRects (aPath, aTransform, rects, count)
function CGPathMoveToPoint (aPath, aTransform, x, y)
function CGPathWithEllipseInRect (aRect)
function CGPathWithRoundedRectangleInRect (aRect, xRadius, yRadius, ne, se, sw, nw)
function CGPathCloseSubpath (aPath)
function CGPathEqualToPath (aPath, anotherPath)
function CGPathGetCurrentPoint (aPath)
function CGPathIsEmpty (aPath)
Variables
var KAPPA = 4.0 * ((SQRT2 - 1.0) / 3.0)
var KAPPA = 4.0 * ((SQRT2 - 1.0) / 3.0)
Function Documentation
function CGBitmapGraphicsContextCreate ()
Returns a new graphics context.
Returns:
CGContext a new graphics context which can be drawn into
Definition at line 140 of file CGContext.j.
References CGGStateCreate().
Referenced by CGBitmapGraphicsContextCreate(), CALayer::display, and CPView::lockFocus.
function CGContextAddArc (aContext , x , y , radius , startAngle , endAngle , clockwise)
Definition at line 190 of file CGContext.j.
References CGPathAddArc().
function CGContextAddArcToPoint (aContext , x1 , y1 , x2 , y2 , radius)
Adds an arc to the current context that ends in the specified point.
Parameters:
aContext the CGContext to edit
x1 the x coordinate of the beginning of the arc
y1 the y coordinate of the beginning of the arc
x2 the x coordinate of the end of the arc
y2 the y coordinate of the end of the arc
radius the radius of the arc to be drawn
Returns:
void
Definition at line 205 of file CGContext.j.
References CGPathAddArcToPoint().
function CGContextAddCurveToPoint (aContext , cp1x , cp1y , cp2x , cp2y , x , y)
Adds a cubic curve to the current context
Parameters:
aContext the CGContext to edit
cp1x the x coordinate of the first control point
cp1y the y coordinate of the first control point
cp2x the x coordinate of the second control point
cp2y the y coordinate of the second control point
x the x coordinate of the end of the curve
y the y coordinate of the end of the curve
Returns:
void
Definition at line 221 of file CGContext.j.
References CGPathAddCurveToPoint().
function CGContextAddEllipseInRect (aContext , aRect)
Draws the outline of an ellipse bounded by a rectangle.
Parameters:
aContext CGContext to draw on
aRect the rectangle bounding the ellipse
Returns:
void
Definition at line 549 of file CGContext.j.
References CGContextAddPath(), CGContextBeginPath(), CGContextClosePath(), and CGPathWithEllipseInRect().
Referenced by CGContextFillEllipseInRect(), and CGContextStrokeEllipseInRect().
function CGContextAddLines (aContext , points , count)
Adds a line to each element in the points array
Parameters:
aContext the CGContext to move
points an array of points that are to be consecutively executed as if they were individual addToPoint calls
count an upper bound on the number of points to use
Returns:
void
Definition at line 233 of file CGContext.j.
References CGPathAddLines().
function CGContextAddLineToPoint (aContext , x , y)
Adds a line from the current point to the x/y
Parameters:
aContext the CGContext to move
x the x coordinate of the end point of the line
y the y coordinate of the end point of the line
Returns:
void
Definition at line 245 of file CGContext.j.
References CGPathAddLineToPoint().
Referenced by CGContextStrokeLineSegments(), CPTableHeaderView::drawRect:, and CPBox::drawRect:.
function CGContextAddPath (aContext , aPath)
Adds aPath to the current path in aContext
Parameters:
aContext the CGContext to add to
aPath the path to be added
Returns:
void
Definition at line 256 of file CGContext.j.
References CGPathAddPath(), CGPathCreateMutable(), and CGPathIsEmpty().
Referenced by CGContextAddEllipseInRect(), CGContextFillRoundedRectangleInRect(), CGContextStrokeRoundedRectangleInRect(), CPBezierPath::fill, and CPBezierPath::stroke.
function CGContextAddQuadCurveToPoint (aContext , cpx , cpy , x , y)
Adds a quadratic curve from the current point to the point specified by x/y, using the control point specified by cpx/cpy
Parameters:
aContext the CGContext to add the curve to
cpx the x coordinate for the curve's control point
cpy the y coordinate for the curve's control point
x the x coordinate for the end point of the curve
y the y coordinate for the end point of the curve
Returns:
void
Definition at line 276 of file CGContext.j.
References CGPathAddQuadCurveToPoint().
function CGContextAddRect (aContext , aRect)
Adds aRect to the current path in the given context
Parameters:
aContext the CGContext to add to
aRect the dimensions of the rectangle to add
Returns:
void
Definition at line 287 of file CGContext.j.
References CGPathAddRect().
Referenced by CGContextStrokeRect().
function CGContextAddRects (aContext , rects , count)
Adds up to count elements from rects to the current path in aContext
Parameters:
aContext the CGContext to add to
rects an array of CGRects to be added to the context's path
the upper bound of elements to be added
Returns:
void
Definition at line 299 of file CGContext.j.
References CGPathAddRects().
Referenced by CGContextClipToRects(), and CGContextFillRects().
function CGContextBeginPath (aContext)
Begins a new subpath in the given context
Parameters:
aContext the CGContext to create a new path in
Returns:
void
Definition at line 309 of file CGContext.j.
References CGPathCreateMutable().
Referenced by CGContextAddEllipseInRect(), CGContextFillEllipseInRect(), CGContextFillRects(), CGContextFillRoundedRectangleInRect(), CGContextStrokeEllipseInRect(), CGContextStrokeLineSegments(), CGContextStrokeRect(), CGContextStrokeRoundedRectangleInRect(), CPTableHeaderView::drawRect:, CPBox::drawRect:, CPBezierPath::fill, and CPBezierPath::stroke.
function CGContextClosePath (aContext)
Closes the currently open subpath, if any, in aContext
Parameters:
aContext the CGContext to close a path in
Returns:
void
Definition at line 320 of file CGContext.j.
References CGPathCloseSubpath().
Referenced by CGContextAddEllipseInRect(), CGContextFillEllipseInRect(), CGContextFillRects(), CGContextFillRoundedRectangleInRect(), CGContextStrokeEllipseInRect(), CGContextStrokeRect(), CGContextStrokeRoundedRectangleInRect(), CPBezierPath::fill, and CPBezierPath::stroke.
function CGContextConcatCTM (aContext , aTransform)
Concatenates the given transformation matrix onto the current transformation matrix in aContext
Parameters:
aContext the CGContext to transform
aTransform the CGAffineTransform to apply to the given context
Returns:
void
Definition at line 408 of file CGContext.j.
Referenced by CALayer::composite, and if().
function CGContextEOFillPath (aContext)
Fills in the area of the current path, using the even-odd fill rule.
Parameters:
aContext the CGContext of the path
Returns:
void
Definition at line 526 of file CGContext.j.
References CGContextDrawPath(), and kCGPathEOFill.
function CGContextFillEllipseInRect (aContext , aRect)
Fills an ellipse bounded by a rectangle.
Parameters:
aContext CGContext to draw on
aRect the rectangle bounding the ellipse
Returns:
void
Definition at line 562 of file CGContext.j.
References CGContextAddEllipseInRect(), CGContextBeginPath(), CGContextClosePath(), and CGContextFillPath().
function CGContextFillPath (aContext)
Fills in the area of the current path, using the non-zero winding number rule.
Parameters:
aContext the CGContext of the path
Returns:
void
Definition at line 536 of file CGContext.j.
References CGContextDrawPath(), and kCGPathFill.
Referenced by CGContextFillEllipseInRect(), CGContextFillRoundedRectangleInRect(), and CPBezierPath::fill.
function CGContextFillRect (aContext , aRect)
Fills a rectangle in the given context with aRect dimensions, using the context's current fill color
Parameters:
aContext the CGContext to draw into
aRect the dimensions of the rectangle to fill
Returns:
void
Definition at line 346 of file CGContext.j.
References CGContextFillRects().
Referenced by CALayer::drawInContext:.
function CGContextFillRects (aContext , rects , count)
Fills a rectangle in the given context for each CGRect in the given array, up to a total of count rects
Parameters:
aContext the CGContext to draw into
rects an array of rects to fill
count the maximum number of rects from the given array to fill
Returns:
void
Definition at line 358 of file CGContext.j.
References CGContextAddRects(), CGContextBeginPath(), CGContextClosePath(), CGContextDrawPath(), and kCGPathFill.
Referenced by CGContextFillRect().
function CGContextFillRoundedRectangleInRect (aContext , aRect , aRadius , ne , se , sw , nw)
Fills a rounded rectangle.
Parameters:
aContext the CGContext to draw into
aRect the base rectangle
aRadius the distance from the rectange corner to the rounded corner
ne set it to YES for a rounded northeast corner
se set it to YES for a rounded southeast corner
sw set it to YES for a rounded southwest corner
nw set it to YES for a rounded northwest corner
Returns:
void
Definition at line 661 of file CGContext.j.
References CGContextAddPath(), CGContextBeginPath(), CGContextClosePath(), CGContextFillPath(), and CGPathWithRoundedRectangleInRect().
Referenced by CPBox::drawRect:.
function CGContextGetCTM (aContext)
Returns the current transformation matrix for the given context
Parameters:
aContext the CGContext for which we are asking for the transform
Returns:
CGAffineTransform the current transformation matrix of the given context
Definition at line 420 of file CGContext.j.
function CGContextMoveToPoint (aContext , x , y)
Moves the current location of aContext to the given x and y coordinates
Parameters:
aContext the CGContext to move
x the x location to move the context to
y the y location to move the context to
Returns:
void
Definition at line 332 of file CGContext.j.
References CGPathCreateMutable(), and CGPathMoveToPoint().
Referenced by CGContextStrokeLineSegments(), CPTableHeaderView::drawRect:, and CPBox::drawRect:.
function CGContextRelease ()
This function is just here for source compatability. It does nothing. CGContext
Definition at line 87 of file CGContext.j.
function CGContextRestoreGState (aContext)
Pops the most recent graphics state of the top of the graphics stack and restores it.
Parameters:
aContext the CGContext to edit
Returns:
void
Definition at line 160 of file CGContext.j.
Referenced by CGContextStrokeRectWithWidth(), CALayer::composite, and CPView::unlockFocus.
function CGContextRetain (aContext)
This function is just here for source compatability. It does nothing.
Parameters:
aContext a CGContext
Returns:
CGContext the context
Definition at line 97 of file CGContext.j.
function CGContextRotateCTM (aContext , anAngle)
Rotates the current context by anAngle radians
Parameters:
aContext the CGContext to rotate
anAngle the amount to rotate, in radians
Returns:
void
Definition at line 432 of file CGContext.j.
References CGAffineTransformRotate().
function CGContextSaveGState (aContext)
Pushes the current graphics state of aContext onto the top of a stack.
Parameters:
aContext the CGContext to edit
Returns:
void
Definition at line 150 of file CGContext.j.
References CGGStateCreateCopy().
Referenced by CGContextStrokeRectWithWidth(), CALayer::composite, and CPView::lockFocus.
function CGContextScaleCTM (aContext , sx , sy)
Scales the current context by sx/sy
Parameters:
aContext the CGContext to scale
sx the amount to scale in the x direction
sy the amount to scale in the y direction
Returns:
void
Definition at line 446 of file CGContext.j.
function CGContextSetAlpha (aContext , anAlpha)
Sets the current alpha value for core graphics drawing operations in the given context .
Parameters:
aContext the CGContext who's alpha value should be updated
anAlpha the new alpha value. 1.0 is completely opaque, 0.0 is completely transparent.
Returns:
void
Definition at line 507 of file CGContext.j.
References MAX, and MIN.
function CGContextSetBlendMode (aContext , aBlendMode)
Definition at line 185 of file CGContext.j.
function CGContextSetFillColor (aContext , aColor)
Sets the current fill color.
Parameters:
aContext the CGContext
aColor the new color for the fill
Returns:
void
Definition at line 632 of file CGContext.j.
Referenced by CALayer::drawInContext:, and CPBox::drawRect:.
function CGContextSetLineCap (aContext , aLineCap)
Definition at line 165 of file CGContext.j.
function CGContextSetLineJoin (aContext , aLineJoin)
Definition at line 170 of file CGContext.j.
function CGContextSetLineWidth (aContext , aLineWidth)
Definition at line 175 of file CGContext.j.
Referenced by CGContextStrokeRectWithWidth(), CPTableHeaderView::drawRect:, CPBox::drawRect:, CPBezierPath::fill, and CPBezierPath::stroke.
function CGContextSetMiterLimit (aContext , aMiterLimit)
Definition at line 180 of file CGContext.j.
function CGContextSetShadow (aContext , aSize , aBlur)
Sets the current offset, and blur for shadows in core graphics drawing operations
Parameters:
aContext the CGContext of the shadow
aSize a CGSize indicating the offset of the shaodw
aBlur a float indicating the blur radius
Returns:
void
Definition at line 475 of file CGContext.j.
function CGContextSetShadowWithColor (aContext , aSize , aBlur , aColor)
Sets the current offset, blur, and color for shadows in core graphics drawing operations
Parameters:
aContext the CGContext of the shadow
aSize a CGSize indicating the offset of the shaodw
aBlur a float indicating the blur radius
aColor a CPColor object indicating the color of the shadow
Returns:
void
Definition at line 492 of file CGContext.j.
function CGContextSetStrokeColor (aContext , aColor)
Sets the current stroke color.
Parameters:
aContext the CGContext
aColor the new color for the stroke
Returns:
void
Definition at line 644 of file CGContext.j.
Referenced by CPBox::drawRect:.
function CGContextStrokeEllipseInRect (aContext , aRect)
Strokes an ellipse bounded by the specified rectangle.
Parameters:
aContext CGContext to draw on
aRect the rectangle bounding the ellipse
Returns:
void
Definition at line 576 of file CGContext.j.
References CGContextAddEllipseInRect(), CGContextBeginPath(), CGContextClosePath(), and CGContextStrokePath().
function CGContextStrokeLineSegments (aContext , points , count)
Strokes multiple line segments.
Parameters:
aContext CGContext to draw on
points an array with an even number of points. The first point is the beginning of the first line segment, the second is the end of the first line segment. The third point is the beginning of second line segment, etc.
count the number of points in the array
Returns:
void
Definition at line 604 of file CGContext.j.
References CGContextAddLineToPoint(), CGContextBeginPath(), CGContextMoveToPoint(), and CGContextStrokePath().
function CGContextStrokePath (aContext)
Paints a line in the current path of the current context.
Parameters:
aContext CGContext to draw on
Returns:
void
Definition at line 589 of file CGContext.j.
References CGContextDrawPath(), and kCGPathStroke.
Referenced by CGContextStrokeEllipseInRect(), CGContextStrokeLineSegments(), CGContextStrokeRoundedRectangleInRect(), CPTableHeaderView::drawRect:, CPBox::drawRect:, and CPBezierPath::stroke.
function CGContextStrokeRect (aContext , aRect)
Strokes a rectangle with the given location into the given context, using the context's current width and color
Parameters:
aContext the CGContext to draw into
aRect a CGRect indicating the dimensions of the rectangle to be drawn
Returns:
void
Definition at line 376 of file CGContext.j.
References CGContextAddRect(), CGContextBeginPath(), CGContextClosePath(), CGContextDrawPath(), and kCGPathStroke.
Referenced by CGContextStrokeRectWithWidth().
function CGContextStrokeRectWithWidth (aContext , aRect , aWidth)
Strokes a rectangle with the given dimensions and the given stroke width
Parameters:
aContext the CGContext to draw into
aRect the CGRect indicating the bounds of the rect to be drawn
aWidth the width with which to stroke the rect
Returns:
void
Definition at line 392 of file CGContext.j.
References CGContextRestoreGState(), CGContextSaveGState(), CGContextSetLineWidth(), and CGContextStrokeRect().
function CGContextStrokeRoundedRectangleInRect (aContext , aRect , aRadius , ne , se , sw , nw)
Strokes a rounded rectangle.
Parameters:
aContext the CGContext to draw into
aRect the base rectangle
aRadius the distance from the rectange corner to the rounded corner
ne set it to YES for a rounded northeast corner
se set it to YES for a rounded southeast corner
sw set it to YES for a rounded southwest corner
nw set it to YES for a rounded northwest corner
Returns:
void
Definition at line 680 of file CGContext.j.
References CGContextAddPath(), CGContextBeginPath(), CGContextClosePath(), CGContextStrokePath(), and CGPathWithRoundedRectangleInRect().
Referenced by CPBox::drawRect:.
function CGContextTranslateCTM (aContext , tx , ty)
Translates the given context by tx in the x direction and ty in the y direction
Parameters:
aContext the CGContext to translate
tx the amount to move in the x direction
ty the amount to move in the y direction
Returns:
void
Definition at line 460 of file CGContext.j.
function CGGStateCreate ()
Creates a new graphics state, which describes all the current values for drawing.
Returns:
a graphics state
Definition at line 116 of file CGContext.j.
References kCGBlendModeNormal, kCGLineCapButt, and kCGLineJoinMiter.
Referenced by CGBitmapGraphicsContextCreate().
function CGGStateCreateCopy (aGState)
Creates a copy of the given graphics state.
Parameters:
aGState the graphics state to copy
Returns:
a copy of the given graphics state
Definition at line 128 of file CGContext.j.
Referenced by CGContextSaveGState().
function CGPathAddArc (aPath , aTransform , x , y , aRadius , aStartAngle , anEndAngle , isClockwise)
Definition at line 83 of file CGPath.j.
References kCGPathElementAddArc.
Referenced by CGContextAddArc(), CGPathAddPath(), and CGPathWithEllipseInRect().
function CGPathAddArcToPoint (aPath , aTransform , x1 , y1 , x2 , y2 , aRadius)
Definition at line 122 of file CGPath.j.
Referenced by CGContextAddArcToPoint().
function CGPathAddCurveToPoint (aPath , aTransform , cp1x , cp1y , cp2x , cp2y , x , y)
Definition at line 126 of file CGPath.j.
References kCGPathElementAddCurveToPoint.
Referenced by CGContextAddCurveToPoint(), CGPathAddPath(), CGPathWithEllipseInRect(), CGPathWithRoundedRectangleInRect(), and CPBezierPath::curveToPoint:controlPoint1:controlPoint2:.
function CGPathAddLines (aPath , aTransform , points , count)
Definition at line 143 of file CGPath.j.
References CGPathAddLineToPoint(), and CGPathMoveToPoint().
Referenced by CPBezierPath::appendBezierPathWithPoints:count:, and CGContextAddLines().
function CGPathAddLineToPoint (aPath , aTransform , x , y)
Definition at line 159 of file CGPath.j.
References kCGPathElementAddLineToPoint.
Referenced by CGContextAddLineToPoint(), CGPathAddLines(), CGPathAddPath(), CGPathAddRects(), CGPathWithRoundedRectangleInRect(), and CPBezierPath::lineToPoint:.
function CGPathAddPath (aPath , aTransform , anotherPath)
Definition at line 170 of file CGPath.j.
References CGPathAddArc(), CGPathAddCurveToPoint(), CGPathAddLineToPoint(), CGPathAddQuadCurveToPoint(), CGPathCloseSubpath(), CGPathMoveToPoint(), kCGPathElementAddArc, kCGPathElementAddCurveToPoint, kCGPathElementAddLineToPoint, kCGPathElementAddQuadCurveToPoint, kCGPathElementCloseSubpath, and kCGPathElementMoveToPoint.
Referenced by CPBezierPath::appendBezierPath:, CPBezierPath::appendBezierPathWithOvalInRect:, CPBezierPath::appendBezierPathWithRoundedRect:xRadius:yRadius:, CGContextAddPath(), and CGPathCreateMutableCopy().
function CGPathAddQuadCurveToPoint (aPath , aTransform , cpx , cpy , x , y)
Definition at line 206 of file CGPath.j.
References kCGPathElementAddQuadCurveToPoint.
Referenced by CGContextAddQuadCurveToPoint(), and CGPathAddPath().
function CGPathAddRect (aPath , aTransform , aRect)
Definition at line 221 of file CGPath.j.
References CGPathAddRects().
Referenced by CPBezierPath::appendBezierPathWithRect:, and CGContextAddRect().
function CGPathAddRects (aPath , aTransform , rects , count)
Definition at line 226 of file CGPath.j.
References CGPathAddLineToPoint(), CGPathCloseSubpath(), and CGPathMoveToPoint().
Referenced by CGContextAddRects(), and CGPathAddRect().
function CGPathCloseSubpath (aPath)
Definition at line 340 of file CGPath.j.
References kCGPathElementCloseSubpath.
Referenced by CGContextClosePath(), CGPathAddPath(), CGPathAddRects(), CGPathWithEllipseInRect(), CGPathWithRoundedRectangleInRect(), and CPBezierPath::closePath.
function CGPathCreateCopy (aPath)
Returns a copy of the given path object.
Definition at line 69 of file CGPath.j.
References CGPathCreateMutableCopy().
function CGPathCreateMutable ()
Returns a new CGPath object.
Definition at line 47 of file CGPath.j.
Referenced by CGContextAddPath(), CGContextBeginPath(), CGContextMoveToPoint(), CGPathCreateMutableCopy(), CGPathWithEllipseInRect(), CGPathWithRoundedRectangleInRect(), CPBezierPath::init, and CPBezierPath::removeAllPoints.
function CGPathCreateMutableCopy (aPath)
Returns a copy of the given path object.
Definition at line 56 of file CGPath.j.
References CGPathAddPath(), and CGPathCreateMutable().
Referenced by CGPathCreateCopy().
function CGPathEqualToPath (aPath , anotherPath)
Definition at line 351 of file CGPath.j.
References j, kCGPathElementAddArc, and kCGPathElementAddArcToPoint.
function CGPathGetCurrentPoint (aPath)
Definition at line 384 of file CGPath.j.
Referenced by CPBezierPath::currentPoint.
function CGPathIsEmpty (aPath)
Definition at line 389 of file CGPath.j.
Referenced by CGContextAddPath(), CGContextDrawPath(), and CPBezierPath::isEmpty.
function CGPathMoveToPoint (aPath , aTransform , x , y)
Definition at line 246 of file CGPath.j.
References kCGPathElementMoveToPoint.
Referenced by CGContextMoveToPoint(), CGPathAddLines(), CGPathAddPath(), CGPathAddRects(), CGPathWithEllipseInRect(), CGPathWithRoundedRectangleInRect(), and CPBezierPath::moveToPoint:.
function CGPathRelease (aPath)
Definition at line 74 of file CGPath.j.
function CGPathRetain (aPath)
Definition at line 78 of file CGPath.j.
function CGPathWithEllipseInRect (aRect)
Definition at line 270 of file CGPath.j.
References CGPathAddArc(), CGPathAddCurveToPoint(), CGPathCloseSubpath(), CGPathCreateMutable(), CGPathMoveToPoint(), and KAPPA.
Referenced by CPBezierPath::appendBezierPathWithOvalInRect:, and CGContextAddEllipseInRect().
function CGPathWithRoundedRectangleInRect (aRect , xRadius , yRadius , ne , se , sw , nw)
Definition at line 294 of file CGPath.j.
References CGPathAddCurveToPoint(), CGPathAddLineToPoint(), CGPathCloseSubpath(), CGPathCreateMutable(), and CGPathMoveToPoint().
Referenced by CPBezierPath::appendBezierPathWithRoundedRect:xRadius:yRadius:, CGContextFillRoundedRectangleInRect(), and CGContextStrokeRoundedRectangleInRect().
Variable Documentation
var KAPPA = 4.0 * ((SQRT2 - 1.0) / 3.0)
Definition at line 268 of file CGPath.j.
var KAPPA = 4.0 * ((SQRT2 - 1.0) / 3.0)
Definition at line 541 of file CGContext.j.
Referenced by CGPathWithEllipseInRect().