Cappuccino: Foundation
Foundation
Classes
class CPJSONPConnection
Allows cross domain connections using JSONP protocol.
class CPArray
A mutable array backed by a JavaScript Array.A mutable array class backed by a JavaScript Array. There is also a CPMutableArray class, but it is just a child class of this class with an empty implementation. All mutable functionality is implemented directly in CPArray.
class CPAttributedString
A mutable character string with attributes.
class CPBundle
Groups information about an application's code & resources.
class CPCoder
Defines methods for use when archiving & restoring (enc/decoding).
class CPCountedSet
An mutable collection which may contain a specific object numerous times.
class CPData
A Cappuccino wrapper for any data type.
class CPDate
A representation of a single point in time.
class CPDictionary
A mutable key-value pair collection.
class CPEnumerator
Defines an interface for enumerators.
class CPException
Used to implement exception handling (creating & raising).
class CPIndexSet
A collection of unique integers.
class CPInvocation
An object representation of a message.
class CPKeyedArchiver
Implements keyed archiving of object graphs (e.g. for storing data).
class CPKeyedUnarchiver
Unarchives objects created using CPKeyedArchiver.
class CPNotification
A notification that can be posted to a CPNotificationCenter.
class CPNotificationCenter
Sends messages (CPNotification) between objects.
class CPNull
An object representation of nil.
class CPNumber
A bridged object to native Javascript numbers.
class CPObject
The root class from which most classes are subclassed.
class CPRunLoop
The main run loop for the application.
class CPSet
An unordered collection of objects.
class CPSortDescriptor
Holds attributes necessary to describe how to sort a set of objects.
class CPString
An immutable string (collection of characters).
class CPTimer
A timer object that can send a message after the given time interval.
class CPUndoManager
A general mechanism for user action "undo".
class CPURLConnection
Provides loading of a URL request.
class CPURLRequest
Contains data obtained during a request made with CPURLConnection.
class CPURLResponse
Protocol agnostic information about a request to a specifc URL.
class CPValue
A generic "value". Can be subclassed to hold specific data types.
Functions
function CPMakeRange (location, length)
function CPCopyRange (aRange)
function CPMakeRangeCopy (aRange)
function CPEmptyRange (aRange)
function CPMaxRange (aRange)
function CPEqualRanges (lhsRange, rhsRange)
function CPLocationInRange (aLocation, aRange)
function CPUnionRange (lhsRange, rhsRange)
function CPIntersectionRange (lhsRange, rhsRange)
function CPRangeInRange (lhsRange, rhsRange)
function CPStringFromRange (aRange)
function CPRangeFromString (aString)
Function Documentation
function CPCopyRange (aRange)
Makes a copy of a CPRange.
Parameters:
aRange the CPRange to copy CPRange
Returns:
CPRange the copy of the range
Definition at line 46 of file CPRange.j.
function CPEmptyRange (aRange)
Sets a range's length to 0.
Parameters:
aRange the range to empty CPRange
Returns:
CPRange the empty range (same as the argument)
Definition at line 68 of file CPRange.j.
function CPEqualRanges (lhsRange , rhsRange)
Determines if two CPRanges are equal.
Parameters:
lhsRange the first CPRange
rhsRange the second CPRange
Returns:
BOOL YES if the two CPRanges are equal.
Definition at line 90 of file CPRange.j.
Referenced by CPIndexSet::isEqualToIndexSet:.
function CPIntersectionRange (lhsRange , rhsRange)
Creates a new CPRange that spans the common range of two CPRanges
Parameters:
lhsRange the first CPRange
rhsRange the second CPRange CPRange
Returns:
CPRange the new CPRange
Definition at line 128 of file CPRange.j.
References CPMakeRange(), CPMaxRange(), MAX, and MIN.
Referenced by CPIndexSet::containsIndexesInRange:, CPAttributedString::isEqualToAttributedString:, CPArray::removeObject:inRange:, and CPArray::removeObjectIdenticalTo:inRange:.
function CPLocationInRange (aLocation , aRange)
Determines if a number is within a specified CPRange.
Parameters:
aLocation the number to check
aRange the CPRange to check within CPRange
Returns:
BOOL YES if aLocation is within the range
Definition at line 102 of file CPRange.j.
References CPMaxRange().
Referenced by CPIndexSet::indexGreaterThanIndex:, CPIndexSet::indexLessThanIndex:, and CPArray::indexOfObjectIdenticalTo:inRange:.
function CPMakeRange (location , length)
Makes a CPRange.
Parameters:
location the location for new range
length the length of the new range CPRange
Returns:
CPRange the new range object
Definition at line 35 of file CPRange.j.
Referenced by CPIntersectionRange(), CPUnionRange(), CPAttributedString::isEqualToAttributedString:, CPString::rangeOfString:options:range:, CPArray::removeObject:inRange:, CPArray::removeObjectIdenticalTo:inRange:, CPTextField::selectedRange, and CPIndexSet::shiftIndexesStartingAtIndex:by:.
function CPMakeRangeCopy (aRange)
Makes a copy of a CPRange.
Parameters:
aRange the CPRange to copy CPRange
Returns:
CPRange the copy of the range
Definition at line 57 of file CPRange.j.
function CPMaxRange (aRange)
Finds the range maximum. (location + length)
Parameters:
aRange the range to calculate a maximum from CPRange
Returns:
int the range maximum
Definition at line 79 of file CPRange.j.
Referenced by CPIndexSet::addIndexesInRange:, CPAttributedString::attribute:atIndex:longestEffectiveRange:inRange:, CPAttributedString::attributedSubstringFromRange:, CPAttributedString::attributesAtIndex:longestEffectiveRange:inRange:, CPIntersectionRange(), CPLocationInRange(), CPRangeInRange(), CPUnionRange(), CPIndexSet::description, CPArray::indexOfObject:inRange:, CPArray::indexOfObjectIdenticalTo:inRange:, CPAttributedString::isEqualToAttributedString:, CPIndexSet::removeIndexesInRange:, CPAttributedString::replaceCharactersInRange:withString:, CPTextField::setSelectedRange:, CPIndexSet::shiftIndexesStartingAtIndex:by:, and CPArray::subarrayWithRange:.
function CPRangeFromString (aString)
Creates a CPRange from the contents of a CPString.
Parameters:
aString the string to create a CPRange from CPRange
Returns:
CPRange the new range
Definition at line 166 of file CPRange.j.
Referenced by CPIndexSet::initWithCoder:.
function CPRangeInRange (lhsRange , rhsRange)
Checks if a range completely contains another range. In other words, if one range is the "super range" of another.
Parameters:
lhsRange the containing range
rhsRange the range we are testing to see if lhsRange contains it CPRange
Returns:
BOOL whether or not lhsRange completely contains rhsRange
Definition at line 144 of file CPRange.j.
References CPMaxRange().
Referenced by CPAttributedString::attribute:atIndex:longestEffectiveRange:inRange:, and CPAttributedString::attributesAtIndex:longestEffectiveRange:inRange:.
function CPStringFromRange (aRange)
Returns a string describing a range.
Parameters:
aRange the range to describe CPRange
Returns:
CPString a describing string
Definition at line 155 of file CPRange.j.
Referenced by CPIndexSet::encodeWithCoder:.
function CPUnionRange (lhsRange , rhsRange)
Creates a new range with the minimum location and a length that extends to the maximum length.
Parameters:
lhsRange the first CPRange
rhsRange the second CPRange CPRange
Returns:
CPRange the new CPRange
Definition at line 115 of file CPRange.j.
References CPMakeRange(), CPMaxRange(), MAX, and MIN.
Referenced by CPIndexSet::addIndexesInRange:, and CPAttributedString::isEqualToAttributedString:.