Cappuccino: AppKit
AppKit
Classes
class CPCib
class CPAlert
class CPFlashView
class CPFontManager
class CPGraphicsContext
class CPRadio
class CPSecureTextField
class CPShadowView
class CPSlider
class CPSplitView
class CPTextField
class CPTheme
class CPThemeBlend
class CPWebView
class CPAnimation
class CPApplication
class CPBezierPath
class CPButton
class CPClipView
class CPCollectionView
class CPColorPanel
class CPColorPicker
class CPColorWell
class CPControl
class CPCookie
class CPDocument
class CPDocumentController
class CPEvent
class CPFlashMovie
class CPFont
class CPImage
class CPImageView
class CPMenu
class CPMenuItem
class CPPanel
class CPPasteboard
class CPPopUpButton
class CPProgressIndicator
class CPResponder
class CPScroller
class CPScrollView
class CPSearchField
class CPSegmentedControl
class CPTabView
class CPTabViewItem
class CPToolbar
class CPToolbarItem
class CPView
class CPWindow
class CPWindowController
Functions
function CGRectContainsRect (lhsRect, rhsRect)
function CGRectIntersectsRect (lhsRect, rhsRect)
function CGRectIntegral (aRect)
function CGRectIntersection (lhsRect, rhsRect)
function CGRectStandardize (aRect)
function CGRectUnion (lhsRect, rhsRect)
function CGPointFromString (aString)
function CGSizeFromString (aString)
function CGRectFromString (aString)
function CGPointFromEvent (anEvent)
function CGInsetFromString (aString)
function CPStringFromCGInset (anInset)
function CPPointCreateCopy (aPoint)
function CPPointMake (x, y)
function CPRectInset (aRect, dX, dY)
function CPRectIntegral (aRect)
function CPRectIntersection (lhsRect, rhsRect)
function CPRectCreateCopy (aRect)
function CPRectMake (x, y, width, height)
function CPRectOffset (aRect, dX, dY)
function CPRectStandardize (aRect)
function CPRectUnion (lhsRect, rhsRect)
function CPSizeCreateCopy (aSize)
function CPSizeMake (width, height)
function CPRectContainsPoint (aRect, aPoint)
function CPRectContainsRect (possibleOuter, possibleInner)
function CPPointEqualToPoint (lhsPoint, rhsPoint)
function CPRectEqualToRect (lhsRect, rhsRect)
function CPRectGetHeight (aRect)
function CPRectGetMaxX (aRect)
function CPRectGetMaxY (aRect)
function CPRectGetMidX (aRect)
function CPRectGetMidY (aRect)
function CPRectGetMinX (aRect)
function CPRectGetMinY (aRect)
function CPRectGetWidth (aRect)
function CPRectIntersectsRect (lhsRect, rhsRect)
function CPRectIsEmpty (aRect)
function CPRectIsNull (aRect)
function CPSizeEqualToSize (lhsSize, rhsSize)
function CPStringFromPoint (aPoint)
function CPStringFromSize (aSize)
function CPStringFromRect (aRect)
function CPPointFromString (aString)
function CPSizeFromString (aString)
function CPRectFromString (aString)
function CPPointFromEvent (anEvent)
function CPSizeMakeZero ()
function CPRectMakeZero ()
function CPPointMakeZero ()
Variables
CGInsetFromCPString = CGInsetFromString
Function Documentation
function CGInsetFromString (aString)
Definition at line 222 of file CGGeometry.j.
function CGPointFromEvent (anEvent)
Definition at line 217 of file CGGeometry.j.
function CGPointFromString (aString)
Definition at line 196 of file CGGeometry.j.
Referenced by CGRectFromString().
function CGRectContainsRect (lhsRect , rhsRect)
Returns a BOOL indicating whether CGRect lhsRect contains CGRect rhsRect. CGRect
Parameters:
lhsRect the CGRect to test if rhsRect is inside of
rhsRect the CGRect to test if it fits inside lhsRect.
Returns:
BOOL YES if rhsRect fits inside lhsRect.
Definition at line 88 of file CGGeometry.j.
References CGRectUnion().
Referenced by CPRectContainsRect(), and CPView::scrollRectToVisible:.
function CGRectFromString (aString)
Definition at line 210 of file CGGeometry.j.
References CGPointFromString(), CGSizeFromString(), and size.
function CGRectIntegral (aRect)
Makes the origin and size of a CGRect all integers. Specifically, by making the southwest corner the origin (rounded down), and the northeast corner a CGSize (rounded up).
Parameters:
aRect the rectangle to operate on
Returns:
CGRect the modified rectangle (same as the input) CGRect
Definition at line 116 of file CGGeometry.j.
References CGRectStandardize().
function CGRectIntersection (lhsRect , rhsRect)
Returns the intersection of the two provided rectangles as a new rectangle.
Parameters:
lhsRect the first rectangle used for calculation
rhsRect the second rectangle used for calculation
Returns:
CGRect the intersection of the two rectangles CGRect
Definition at line 140 of file CGGeometry.j.
References MAX, and MIN.
Referenced by CGRectIntersectsRect(), CPView::scrollRectToVisible:, and CPView::visibleRect.
function CGRectIntersectsRect (lhsRect , rhsRect)
Returns YES if the two rectangles intersect CGRect
Parameters:
lhsRect the first CGRect
rhsRect the second CGRect
Returns:
BOOL YES if the two rectangles have any common spaces, and NO, otherwise.
Definition at line 102 of file CGGeometry.j.
References CGRectIntersection().
function CGRectStandardize (aRect)
Definition at line 156 of file CGGeometry.j.
References height, and width.
Referenced by CGRectIntegral().
function CGRectUnion (lhsRect , rhsRect)
Definition at line 177 of file CGGeometry.j.
References CGRectNull, MAX, and MIN.
Referenced by CGRectContainsRect(), and CPView::setNeedsDisplayInRect:.
function CGSizeFromString (aString)
Definition at line 203 of file CGGeometry.j.
References height, and width.
Referenced by CGRectFromString().
function CPPointCreateCopy (aPoint)
Creates a copy of a specified point and returns the copy CGPoint
Parameters:
the point to be copied
Returns:
CGPoint the copy of the provided CGPoint
Definition at line 47 of file CPGeometry.j.
Referenced by CPRectCreateCopy().
function CPPointEqualToPoint (lhsPoint , rhsPoint)
Tests whether the two CGPoints are equal to each other by comparing their x and y members.
Parameters:
lhsPoint the first CGPoint to check
rhsPoint the second CGPoint to check
Returns:
BOOL YES if the two points have the same x's, and the same y's.
Definition at line 250 of file CPGeometry.j.
Referenced by CPRectEqualToRect().
function CPPointFromEvent (anEvent)
CGPoint
Parameters:
anEvent
Returns:
CGPoint
Definition at line 472 of file CPGeometry.j.
References CPPointMake().
function CPPointFromString (aString)
Returns a CGPoint from a string with a comma separated pair of integers. CGPoint
Parameters:
aString a string containing two comma separated integers
Returns:
CGPoint the point object created from the string
Definition at line 434 of file CPGeometry.j.
Referenced by CPRectFromString(), and CPKeyedUnarchiver::decodePointForKey:.
function CPPointMake (x , y)
Makes a CGPoint object out of two numbers provided as arguments CGPoint
Parameters:
x the x-coordinate of the CGPoint
y the y-coordinate of the CGPoint
Returns:
CGPoint a CGPoint with an X and Y coordinate equal to the function arguments
Definition at line 59 of file CPGeometry.j.
Referenced by CPPointFromEvent(), CPPointMakeZero(), CPRectMake(), and CPKeyedUnarchiver::decodePointForKey:.
function CPPointMakeZero ()
Returns a point located at (0, 0). CGPoint
Returns:
CGPoint a point located at (0, 0)
Definition at line 502 of file CPGeometry.j.
References CPPointMake().
function CPRectContainsPoint (aRect , aPoint)
Returns YES if the CGRect, aRect, contains the CGPoint, aPoint.
Parameters:
aRect the rectangle to test with
aPoint the point to test with CGRect
Returns:
BOOL YES if the rectangle contains the point, NO otherwise.
Definition at line 221 of file CPGeometry.j.
References CPRectGetMaxX(), CPRectGetMaxY(), CPRectGetMinX(), and CPRectGetMinY().
Referenced by CPClipView::autoscroll:, CPView::hitTest:, and CPSearchField::trackMouse:.
function CPRectContainsRect (possibleOuter , possibleInner)
Returns a BOOL indicating whether CGRect possibleOuter contains CGRect possibleInner. CGRect
Parameters:
possibleOuter the CGRect to test if possibleInner is inside of
possibleInner the CGRect to test if it fits inside possibleOuter.
Returns:
BOOL YES if possibleInner fits inside possibleOuter.
Definition at line 237 of file CPGeometry.j.
References CGRectContainsRect().
function CPRectCreateCopy (aRect)
Creates a copy of the provided rectangle CGRect
Parameters:
aRect the CGRect that will be copied
Returns:
CGRect the rectangle copy
Definition at line 115 of file CPGeometry.j.
References CPPointCreateCopy(), CPSizeCreateCopy(), and size.
Referenced by CPRectStandardize().
function CPRectEqualToRect (lhsRect , rhsRect)
Test whether the two CGRects have the same origin and size CGRect
Parameters:
lhsRect the first CGRect to compare
rhsRect the second CGRect to compare
Returns:
BOOL YES if the two rectangles have the same origin and size. NO, otherwise.
Definition at line 262 of file CPGeometry.j.
References CPPointEqualToPoint(), and CPSizeEqualToSize().
function CPRectFromString (aString)
Returns a CGRect created from a string. CGRect
Parameters:
aString a string in the form generated by CPStringFromRect
Returns:
CGRect the rectangle created from the string
Definition at line 460 of file CPGeometry.j.
References CPPointFromString(), CPSizeFromString(), and size.
Referenced by CPKeyedUnarchiver::decodeRectForKey:.
function CPRectGetHeight (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
int
Definition at line 273 of file CPGeometry.j.
Referenced by CPRectStandardize().
function CPRectGetMaxX (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
int
Definition at line 283 of file CPGeometry.j.
Referenced by CPRectContainsPoint(), CPRectIntersection(), and CPRectUnion().
function CPRectGetMaxY (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
int
Definition at line 293 of file CPGeometry.j.
Referenced by CPRectContainsPoint(), CPRectIntersection(), and CPRectUnion().
function CPRectGetMidX (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
float
Definition at line 303 of file CPGeometry.j.
function CPRectGetMidY (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
float
Definition at line 313 of file CPGeometry.j.
function CPRectGetMinX (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
int
Definition at line 323 of file CPGeometry.j.
Referenced by CPRectContainsPoint(), CPRectIntersection(), and CPRectUnion().
function CPRectGetMinY (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
int
Definition at line 333 of file CPGeometry.j.
Referenced by CPRectContainsPoint(), CPRectIntersection(), and CPRectUnion().
function CPRectGetWidth (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
int
Definition at line 343 of file CPGeometry.j.
Referenced by CPRectStandardize().
function CPRectInset (aRect , dX , dY)
Makes a CGRect with an origin and size equal to aRect less the dX/dY insets specified.
Parameters:
dX the size of the inset in the x-axis
dY the size of the inset in the y-axis CGRect
Returns:
CGRect a rectangle like aRect with an inset
Definition at line 71 of file CPGeometry.j.
References CPRectMake().
function CPRectIntegral (aRect)
CGRect
Returns:
void
Deprecated:
Definition at line 83 of file CPGeometry.j.
function CPRectIntersection (lhsRect , rhsRect)
Returns the intersection of the two provided rectangles as a new rectangle CGRect
Parameters:
lhsRect the first rectangle used for calculation
rhsRect the second rectangle used for calculation
Returns:
CGRect the intersection of the two rectangles
Definition at line 96 of file CPGeometry.j.
References CPRectGetMaxX(), CPRectGetMaxY(), CPRectGetMinX(), CPRectGetMinY(), CPRectIsEmpty(), CPRectMake(), and CPRectMakeZero().
Referenced by CPRectIntersectsRect().
function CPRectIntersectsRect (lhsRect , rhsRect)
Returns YES if the two rectangles intersect CGRect
Parameters:
lhsRect the first CGRect
rhsRect the second CGRect
Returns:
BOOL YES if the two rectangles have any common spaces, and NO, otherwise.
Definition at line 355 of file CPGeometry.j.
References CPRectIntersection(), and CPRectIsEmpty().
function CPRectIsEmpty (aRect)
Returns YES if the CGRect has no area. The test is performed by checking if the width and height are both zero. CGRect
Parameters:
aRect the CGRect to test
Returns:
BOOL YES if the CGRect has no area, and NO, otherwise.
Definition at line 367 of file CPGeometry.j.
Referenced by CPRectIntersection(), and CPRectIntersectsRect().
function CPRectIsNull (aRect)
Returns YES if the CGRect has no area. The test is performed by checking if the width and height are both zero. CGRect
Returns:
BOOL YES if the CGRect has no area, and NO, otherwise.
Definition at line 378 of file CPGeometry.j.
function CPRectMake (x , y , width , height)
Returns a CGRect made of the specified arguments CGRect
Parameters:
x the x-coordinate of the rectangle's origin
y the y-coordinate of the rectangle's origin
width the width of the new rectangle
height the height of the new rectangle
Returns:
CGRect the new rectangle
Definition at line 129 of file CPGeometry.j.
References CPPointMake(), CPSizeMake(), height, size, and width.
Referenced by CPRectInset(), CPRectIntersection(), CPRectMakeZero(), CPRectOffset(), CPRectUnion(), CPSliderColorPicker::initView, CPColorWheelColorPicker::initView, and CPSegmentedControl::rectForEphemeralSubviewNamed:.
function CPRectMakeZero ()
Returns a rectangle at origin (0,0) and size of (0,0). CGRect
Returns:
CGRect a zeroed out CGRect
Definition at line 492 of file CPGeometry.j.
References CPRectMake().
Referenced by CPRectIntersection(), and CPKeyedUnarchiver::decodeRectForKey:.
function CPRectOffset (aRect , dX , dY)
Creates a new rectangle with its origin offset by dX and dY. CGRect
Parameters:
aRect the rectangle to copy the origin and size from
dX the amount added to the x-size of the new rectangle
dY the amount added to the y-size of the new rectangle
Returns:
CGRect the new rectangle with modified size
Definition at line 142 of file CPGeometry.j.
References CPRectMake().
function CPRectStandardize (aRect)
CGRect
Parameters:
aRect a CGRect
Returns:
CGRect
Definition at line 152 of file CPGeometry.j.
References CPRectCreateCopy(), CPRectGetHeight(), CPRectGetWidth(), height, and width.
function CPRectUnion (lhsRect , rhsRect)
Returns the smallest rectangle that can contain the two argument CGRects. CGRect
Parameters:
lhsRect the first CGRect to use for the union calculation
rhsRect the second CGRect to use for the union calculation
Returns:
CGRect the union rectangle
Definition at line 180 of file CPGeometry.j.
References CPRectGetMaxX(), CPRectGetMaxY(), CPRectGetMinX(), CPRectGetMinY(), and CPRectMake().
function CPSizeCreateCopy (aSize)
Creates and returns a copy of the provided CGSize CGSize
Parameters:
aSize the CGSize to copy
Returns:
CGSize the copy of the CGSize
Definition at line 196 of file CPGeometry.j.
References height, and width.
Referenced by CPRectCreateCopy(), and CPImage::initByReferencingFile:size:.
function CPSizeEqualToSize (lhsSize , rhsSize)
Returns YES if the two CGSizes are identical. CGSize
Parameters:
lhsSize the first CGSize to compare
rhsSize the second CGSize to compare
Returns:
BOOL YES if the two sizes are identical. NO, otherwise.
Definition at line 390 of file CPGeometry.j.
Referenced by CPRectEqualToRect().
function CPSizeFromString (aString)
Returns a CGSize from a string containing a pair of comma separated integers. CGSize
Parameters:
aString a string containing two comma separated integers
Returns:
CGSize the size object created from the string
Definition at line 447 of file CPGeometry.j.
References height, and width.
Referenced by CPRectFromString(), and CPKeyedUnarchiver::decodeSizeForKey:.
function CPSizeMake (width , height)
Creates and returns a new CGSize object from the provided dimensions. CGSize
Parameters:
width the width for the new CGSize
height the height for the new CGSize
Returns:
CGSize the new CGSize
Definition at line 208 of file CPGeometry.j.
References height, and width.
Referenced by CPClipView::autoscroll:, CPRectMake(), CPSizeMakeZero(), and CPKeyedUnarchiver::decodeSizeForKey:.
function CPSizeMakeZero ()
Returns a zero sized CGSize. CGSize
Returns:
CGSize a size object with zeros for width and height
Definition at line 482 of file CPGeometry.j.
References CPSizeMake().
function CPStringFromCGInset (anInset)
Definition at line 231 of file CGGeometry.j.
function CPStringFromPoint (aPoint)
Returns a human readable string of the provided CGPoint. CGPoint
Parameters:
aPoint the point to represent
Returns:
CGPoint a string representation of the CGPoint
Definition at line 401 of file CPGeometry.j.
Referenced by CPStringFromRect().
function CPStringFromRect (aRect)
Returns a human readable string of the provided CGRect. CGRect
Parameters:
aRect the rectangle to represent
Returns:
CGString the string representation of the rectangle
Definition at line 423 of file CPGeometry.j.
References CPStringFromPoint(), and CPStringFromSize().
function CPStringFromSize (aSize)
Returns a human readable string of the provided CGSize. CGSize
Parameters:
aSize the size to represent
Returns:
CGSize a string representation of the CGSize
Definition at line 412 of file CPGeometry.j.
Referenced by CPStringFromRect().
Variable Documentation
CGInsetFromCPString = CGInsetFromString
Definition at line 229 of file CGGeometry.j.